#!/usr/bin/env python3
"""Compile the original sprite sheets into bounded RGB565 arrays (Pillow)."""
from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
KEY = 0xF81F


def convert(name, size):
    src = Image.open(ROOT / 'assets' / f'{name}.png').convert('RGBA')
    if name == 'reinforced':
        assert src.size == (1774, 887)
    else:
        assert src.width == src.height and 512 <= src.width <= 2048
    edge = src.width
    columns, row_count = (2, 1) if name == 'reinforced' else (1, 1) if name == 'ember_crate' else (4, 4)
    rows = []
    for row in range(row_count):
        for col in range(columns):
            bounds = (col*src.width//columns, row*src.height//row_count,
                      (col+1)*src.width//columns, (row+1)*src.height//row_count)
            if name == 'reinforced':
                # Same-sized square crops preserve both states' footprint/baseline.
                bounds = [(144, 118, 800, 774), (976, 118, 1632, 774)][col]
            if name == 'ember_crate':
                bounds = (170, 172, 1098, 1100)
            if name == 'biomes':
                # This generated sheet has four separate, nonuniform row bands.
                # Compile measured crop-safe source rectangles, never adjacent rows.
                assert edge == 1254
                tops = [0, 301, 603, 876]
                bottoms = [289, 590, 874, 1254]
                lefts = [6, 320, 633, 946]
                rights = [309, 622, 935, 1248]
                bounds = (lefts[col], tops[row], rights[col], bottoms[row])
            frame = src.crop(bounds)
            frame = frame.resize((size, size), Image.Resampling.NEAREST)
            pixels = []
            pixels_rgba = frame.get_flattened_data() if hasattr(frame, "get_flattened_data") else frame.getdata()
            for r, g, b, a in pixels_rgba:
                v = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
                pixels.append(KEY if a < 128 else (v if v != KEY else v ^ 1))
            rows.append(pixels)
    out = ROOT / 'src' / 'generated' / f'{name}.inc'
    with out.open('w') as f:
        f.write('// Generated by tools/convert_assets.py; do not edit.\n')
        symbol = 'effect_atlas' if name == 'effects' else name
        f.write(f'static const uint16_t bc_{symbol}[{len(rows)}][{size*size}] = {{\n')
        for pixels in rows:
            f.write(' {\n')
            for start in range(0, len(pixels), 16):
                f.write('  ' + ','.join(f'0x{x:04x}' for x in pixels[start:start+16]) + ',\n')
            f.write(' },\n')
        f.write('};\n')
    print(f'{name}: {len(rows)} x {size} x {size} x 2 = {len(rows)*size*size*2:,} static bytes')


convert('runner', 48)
convert('greenhouse', 32)

convert('effects', 32)

convert('ember', 32)
convert('volt', 32)
convert('gilt', 32)
convert('biomes', 32)

convert('reinforced', 32)

convert('ember_crate', 32)
