#!/usr/bin/env python3
"""Deterministic measured-cell ImageGen atlas conversion; requires Pillow."""
from pathlib import Path
from PIL import Image
import json, hashlib
ROOT=Path(__file__).resolve().parents[1]
GAME=ROOT.name
W,H=(80, 44)
im=Image.open(ROOT/'assets/hires_atlas_v2.png').convert('RGBA')
rows=[0, 276, 538, 860, 1122]
frames=[]
bounds=[]
for row in range(4):
 for col in range(4):
  box=(col*im.width//4,rows[row],(col+1)*im.width//4,rows[row+1])
  crop=im.crop(box)
  alpha=crop.getchannel('A').point(lambda a:255 if a>=160 else 0)
  bb=alpha.getbbox()
  if not bb: raise ValueError('Empty atlas cell')
  bounds.append([box[0]+bb[0],box[1]+bb[1],box[0]+bb[2],box[1]+bb[3]])
  crop=crop.crop(bb)
  target=Image.new('RGBA',(W,H))
  if GAME=='frog_hop':
   cap=[(42,42),(90,30),(96,31),(46,38)][row]
  elif GAME=='skyline_leap':
   cap=(54,46) if row<2 else ((40,36) if row==2 else (38,38))
   if row==3 and col in (1,3):cap=(62,72)
  else: cap=(W-2,H-2)
  crop.thumbnail(cap,Image.Resampling.LANCZOS)
  if GAME=='frog_hop' and row in (1,2):crop=crop.resize(cap,Image.Resampling.LANCZOS)
  if GAME=='space_invaders' and row<3:crop=crop.resize((W-2,H-2),Image.Resampling.LANCZOS)
  at=((W-crop.width)//2,(H-crop.height)//2)
  if GAME=='skyline_leap' and row<3:at=(at[0],H-crop.height)
  if GAME=='skyline_leap' and row==3 and col in (1,3):at=(at[0],H-crop.height)
  target.paste(crop,at)
  frames.append(target)
values=[]
for frame in frames:
 vals=[]
 for r,g,b,a in frame.getdata():
  v=((r>>3)<<11)|((g>>2)<<5)|(b>>3)
  vals.append(0 if a<160 else max(v,1))
 values.append(vals)
lines=['/* Generated by tools/convert_hires.py; original ImageGen art. */',f'enum {{ HI_ART_W = {W}, HI_ART_H = {H} }};',f'static const uint16_t hi_art[16][{W*H}] = {{']
for vals in values:
 lines.append(' {')
 for i in range(0,len(vals),16):lines.append('  '+','.join(f'0x{v:04x}' for v in vals[i:i+16])+',')
 lines.append(' },')
lines.append('};')
(ROOT/'src/generated/hires_art.inc').write_text('\n'.join(lines)+'\n')
preview=Image.new('RGBA',(W*4,H*4))
for i,f in enumerate(frames):preview.paste(f,((i%4)*W,(i//4)*H))
preview.save(ROOT/'assets/hires_compiled_preview.png')
p=ROOT/'assets/hires_provenance.json'
d=json.loads(p.read_text());d['conversion']={'cell_dimensions':[W,H],'measured_opaque_bounds':bounds,'resize':'Lanczos from measured original ImageGen crops; fitted to existing collision silhouettes; alpha >=160 to RGB565 chroma key 0','atlas_static_bytes':W*H*16*2}
if GAME=='skyline_leap':
 bg=Image.open(ROOT/'assets/hires_city_v2.png').convert('RGB').resize((384,154),Image.Resampling.LANCZOS)
 vals=[((r>>3)<<11)|((g>>2)<<5)|(b>>3) for r,g,b in bg.getdata()]
 lines=['/* Generated background; original ImageGen art. */','static const uint16_t hi_city[384 * 154] = {']
 for i in range(0,len(vals),16):lines.append(' '+','.join(f'0x{v:04x}' for v in vals[i:i+16])+',')
 lines.append('};');(ROOT/'src/generated/hires_city.inc').write_text('\n'.join(lines)+'\n')
 d['conversion']['background_static_bytes']=384*154*2
p.write_text(json.dumps(d,indent=2)+'\n')
print(GAME,d['conversion']['atlas_static_bytes'],'atlas bytes')
