#!/usr/bin/env python3
"""Reproducible offline conversion of the original ImageGen space backdrop."""
from pathlib import Path
from PIL import Image
ROOT = Path(__file__).resolve().parents[1]
image = Image.open(ROOT / 'assets/space_backdrop_v3.png').convert('RGB')
image = image.resize((384, 192), Image.Resampling.LANCZOS)
pixels = [((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3) for r, g, b in image.getdata()]
lines = ['/* Original ImageGen art; generated by tools/convert_background.py. */',
         'static const uint16_t space_backdrop[384U * 192U] = {']
lines += ['    ' + ','.join(f'0x{p:04x}' for p in pixels[i:i + 16]) + ','
          for i in range(0, len(pixels), 16)]
lines += ['};']
(ROOT / 'src/generated/space_backdrop.inc').write_text('\n'.join(lines) + '\n')
