#!/usr/bin/env python3
"""Rebuild reviewed high-resolution ImageGen materials as bounded RGB565 arrays."""
from pathlib import Path
import json
from PIL import Image
ROOT = Path(__file__).resolve().parents[1]
KEY = 0xf81f
def rgb565(r,g,b):
    n = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
    return n ^ 1 if n == KEY else n
def main():
    spec=json.loads((ROOT/'assets/presentation_provenance.json').read_text())
    source=Image.open(ROOT/'assets'/spec['source']).convert('RGBA')
    lines=['// SPDX-License-Identifier: MIT','// Generated by tools/convert_presentation.py; do not edit.','enum { PRESENTATION_CHROMA = 0xf81f };']
    total=0
    for group in spec['groups']:
        size=group['size']; rects=group['rects']
        row_width=size*2 if group.get('mirror_rows',False) else size
        lines.append(f"static const uint16_t {group['name']}[{len(rects)}][{row_width*size}] = {{")
        for index,rect in enumerate(rects):
            crop=source.crop(rect)
            if index>=group['opaque']:
                side=max(crop.size)
                padded=Image.new('RGBA',(side,side))
                padded.alpha_composite(crop,((side-crop.width)//2,(side-crop.height)//2))
                crop=padded
            image=crop.resize((size,size),Image.Resampling.NEAREST)
            values=[KEY if a<160 and index>=group['opaque'] else rgb565(r,g,b) for r,g,b,a in image.getdata()]
            if group.get('mirror_rows',False):
                values=[v for y in range(size) for v in
                    (values[y*size:(y+1)*size]+list(reversed(values[y*size:(y+1)*size])))]
            lines.append(' {')
            lines += ['  '+','.join(f'0x{v:04x}' for v in values[i:i+16])+',' for i in range(0,len(values),16)]
            lines.append(' },')
            total+=row_width*size*2
        lines.append('};')
    (ROOT/'src/generated/presentation_assets.inc').write_text('\n'.join(lines)+'\n')
    print(f'{ROOT.name}: {total} RGB565 bytes')
if __name__=='__main__': main()
