#!/usr/bin/env python3

"""Convert the reviewed ImageGen 3x2 dice sheet to fixed RGB565 sprites."""

from __future__ import annotations

import argparse
import pathlib

from PIL import Image


GRID_COLUMNS = 3
GRID_ROWS = 2
SPRITE_SIZE = 46
CHROMA_KEY = 0xF81F


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)


def square_crop(cell: Image.Image) -> Image.Image:
    alpha = cell.getchannel("A")
    bbox = alpha.point(lambda value: 255 if value >= 24 else 0).getbbox()
    if bbox is None:
        raise ValueError("atlas cell has no visible pixels")
    left, top, right, bottom = bbox
    width = right - left
    height = bottom - top
    side = max(width, height)
    center_x = (left + right) // 2
    center_y = (top + bottom) // 2
    left = max(0, center_x - side // 2)
    top = max(0, center_y - side // 2)
    right = min(cell.width, left + side)
    bottom = min(cell.height, top + side)
    left = max(0, right - side)
    top = max(0, bottom - side)
    return cell.crop((left, top, right, bottom))


def convert(source: pathlib.Path, destination: pathlib.Path) -> None:
    image = Image.open(source).convert("RGBA")
    if image.width % GRID_COLUMNS != 0 or image.height % GRID_ROWS != 0:
        raise ValueError("source must divide exactly into a 3x2 atlas")
    cell_width = image.width // GRID_COLUMNS
    cell_height = image.height // GRID_ROWS
    sprites: list[list[int]] = []
    for face in range(6):
        column = face % GRID_COLUMNS
        row = face // GRID_COLUMNS
        cell = image.crop((
            column * cell_width,
            row * cell_height,
            (column + 1) * cell_width,
            (row + 1) * cell_height,
        ))
        sprite = square_crop(cell).resize(
            (SPRITE_SIZE, SPRITE_SIZE), Image.Resampling.NEAREST)
        pixels: list[int] = []
        source_pixels = sprite.load()
        for y in range(SPRITE_SIZE):
            for x in range(SPRITE_SIZE):
                red, green, blue, alpha = source_pixels[x, y]
                pixels.append(
                    CHROMA_KEY if alpha < 96 else rgb565(red, green, blue))
        if all(pixel == CHROMA_KEY for pixel in pixels):
            raise ValueError(f"face {face + 1} converted to an empty sprite")
        sprites.append(pixels)

    lines = [
        "// SPDX-License-Identifier: MIT",
        "// Generated by tools/png_to_dice_atlas.py; do not edit.",
        "",
        f"enum {{ P4_YAHTZEE_DIE_SPRITE_SIZE = {SPRITE_SIZE} }};",
        f"#define P4_YAHTZEE_DIE_CHROMA UINT16_C(0x{CHROMA_KEY:04x})",
        "static const uint16_t s_p4_yahtzee_dice[6]",
        "    [P4_YAHTZEE_DIE_SPRITE_SIZE * P4_YAHTZEE_DIE_SPRITE_SIZE] = {",
    ]
    for face, pixels in enumerate(sprites, start=1):
        lines.append(f"    {{ /* face {face} */")
        for offset in range(0, len(pixels), 12):
            chunk = ", ".join(
                f"UINT16_C(0x{pixel:04x})" for pixel in pixels[offset:offset + 12])
            lines.append(f"        {chunk},")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    destination.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=pathlib.Path)
    parser.add_argument("destination", type=pathlib.Path)
    args = parser.parse_args()
    convert(args.source, args.destination)


if __name__ == "__main__":
    main()
