#!/usr/bin/env python3
"""Compile original ImageGen materials and the measured original title frog."""
from pathlib import Path
from PIL import Image
import hashlib, json
ROOT = Path(__file__).resolve().parents[1]
source = Image.open(ROOT/'assets/environment_v1.png').convert('RGB')
W, H = 128, 80
bounds = [(0,0,source.width//2,source.height//2),
          (source.width//2,0,source.width,source.height//2),
          (0,source.height//2,source.width//2,source.height),
          (source.width//2,source.height//2,source.width,source.height)]
frames = [source.crop(b).resize((W,H),Image.Resampling.LANCZOS) for b in bounds]
# The title keeps higher detail from the original frog, not the gameplay atlas.
hero_source = Image.open(ROOT/'assets/hires_atlas_v2.png').convert('RGBA')
hero_bounds = (100,95,285,245)
hero = hero_source.crop(hero_bounds)
hero.thumbnail((128,104),Image.Resampling.LANCZOS)
hero_frame = Image.new('RGBA',(128,104))
hero_frame.paste(hero,((128-hero.width)//2,(104-hero.height)//2))
def pixels(image,alpha=False):
 out=[]
 for p in image.getdata():
  r,g,b=p[:3]; v=((r>>3)<<11)|((g>>2)<<5)|(b>>3)
  out.append(0 if alpha and p[3]<160 else max(v,1))
 return out
lines=['/* Generated by tools/convert_environment.py; original ImageGen textures. */',
       'enum { TERRAIN_W=128, TERRAIN_H=80 };',
       'static const uint16_t terrain_art[4][128*80] = {']
for f in frames:
 vals=pixels(f); lines.append('{')
 for i in range(0,len(vals),16):lines.append(','.join(f'0x{v:04x}' for v in vals[i:i+16])+',')
 lines.append('},')
lines.extend(['};','static const uint16_t title_frog[128*104] = {'])
vals=pixels(hero_frame,True)
for i in range(0,len(vals),16):lines.append(','.join(f'0x{v:04x}' for v in vals[i:i+16])+',')
lines.append('};')
(ROOT/'src/generated/environment.inc').write_text('\n'.join(lines)+'\n')
preview=Image.new('RGB',(256,160))
for i,f in enumerate(frames):preview.paste(f,((i%2)*W,(i//2)*H))
preview.save(ROOT/'assets/environment_compiled_preview.png')
hero_frame.save(ROOT/'assets/title_frog_preview.png')
p=ROOT/'assets/environment_provenance.json'; data=json.loads(p.read_text())
data['conversion']={'measured_quadrants':bounds,'texture_size':[W,H],
 'sampling':'Lanczos reduction to RGB565; tile at one source pixel per native pixel, fallback samples same material field',
 'texture_static_bytes':4*W*H*2,'hero_source':'assets/hires_atlas_v2.png','hero_crop':hero_bounds,
 'hero_size':[128,104],'hero_sampling':'Lanczos, aspect preserved, alpha >=160, RGB565 key 0',
 'hero_static_bytes':128*104*2,'total_static_bytes':4*W*H*2+128*104*2}
p.write_text(json.dumps(data,indent=2)+'\n')
print('Environment and title frog:',data['conversion']['total_static_bytes'],'bytes')
