#!/usr/bin/env python3
"""Deterministically pack the illustrated opening; no runtime image decoding."""
from pathlib import Path
import hashlib
import json
from PIL import Image, ImageOps

GAME = Path(__file__).resolve().parents[1]
SOURCE = GAME / "assets/source/title-illustrated-v2.png"


def rgb565(rgb):
    r, g, b = rgb
    return ((r & 248) << 8) | ((g & 252) << 3) | (b >> 3)


def build():
    source = Image.open(SOURCE).convert("RGB")
    lines = ["// SPDX-License-Identifier: LicenseRef-LORD-Permission",
             "// Generated by tools/build_illustrated_title.py; do not edit.",
             "#ifndef LORD_ILLUSTRATED_TITLE_H", "#define LORD_ILLUSTRATED_TITLE_H",
             "#include <stdint.h>"]
    outputs = []
    for name, size in (("native", (736, 306)), ("fallback", (304, 126))):
        resized = ImageOps.fit(source, size, method=Image.Resampling.LANCZOS)
        indexed = resized.quantize(colors=256, method=Image.Quantize.MEDIANCUT,
                                   dither=Image.Dither.NONE)
        palette = indexed.getpalette()
        colors = [rgb565(palette[i:i + 3]) for i in range(0, 768, 3)]
        pixels = indexed.tobytes()
        lines += [f"enum {{ LORD_TITLE_{name.upper()}_W = {size[0]},",
                  f"       LORD_TITLE_{name.upper()}_H = {size[1]} }};",
                  f"static const uint16_t s_lord_title_{name}_palette[256] = {{"]
        for start in range(0, 256, 12):
            lines.append("    " + ",".join(f"0x{v:04x}" for v in colors[start:start + 12]) + ",")
        lines += ["};", f"static const uint8_t s_lord_title_{name}_pixels[{len(pixels)}] = {{"]
        for start in range(0, len(pixels), 32):
            lines.append("    " + ",".join(str(v) for v in pixels[start:start + 32]) + ",")
        lines += ["};"]
        rgb = bytes(v for p in pixels for v in (
            ((colors[p] >> 11) & 31) * 255 // 31,
            ((colors[p] >> 5) & 63) * 255 // 63,
            (colors[p] & 31) * 255 // 31))
        preview = GAME / f"assets/title-illustrated-{name}.png"
        Image.frombytes("RGB", size, rgb).save(preview, optimize=True)
        outputs.append({"name": name, "size": size, "indexed_bytes": len(pixels),
                        "palette_bytes": 512, "preview_sha256": hashlib.sha256(preview.read_bytes()).hexdigest()})
    lines += ["#endif", ""]
    target = GAME / "src/generated/lord_illustrated_title.h"
    target.write_text("\n".join(lines))
    print(json.dumps({"outputs": outputs, "header_sha256": hashlib.sha256(target.read_bytes()).hexdigest()}))


if __name__ == "__main__":
    build()
