#!/usr/bin/env python3
"""Build the checked-in 16-color RGB565 LORD title art."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image


WIDTH = 320
HEIGHT = 136
ANSI_RGB = (
    (0, 0, 0),
    (0, 0, 170),
    (0, 170, 0),
    (0, 170, 170),
    (170, 0, 0),
    (170, 0, 170),
    (170, 85, 0),
    (170, 170, 170),
    (85, 85, 85),
    (85, 85, 255),
    (85, 255, 85),
    (85, 255, 255),
    (255, 85, 85),
    (255, 85, 255),
    (255, 255, 85),
    (255, 255, 255),
)


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)


def build(input_path: Path, preview_path: Path, header_path: Path) -> None:
    source = Image.open(input_path).convert("RGB")
    resized = source.resize((WIDTH, HEIGHT), Image.Resampling.BOX)
    palette = Image.new("P", (1, 1))
    flat_palette = [component for color in ANSI_RGB for component in color]
    flat_palette.extend([0] * (768 - len(flat_palette)))
    palette.putpalette(flat_palette)
    indexed = resized.quantize(
        palette=palette,
        dither=Image.Dither.FLOYDSTEINBERG,
    )
    final = indexed.convert("RGB")
    preview_path.parent.mkdir(parents=True, exist_ok=True)
    final.save(preview_path, optimize=True)

    raw = final.tobytes()
    values = [
        rgb565(raw[index], raw[index + 1], raw[index + 2])
        for index in range(0, len(raw), 3)
    ]
    lines = [
        "// SPDX-License-Identifier: LicenseRef-LORD-Permission",
        "// Generated by games/lord/tools/build_title_art.py; do not hand edit.",
        "",
        "#ifndef P4_LORD_TITLE_ART_H",
        "#define P4_LORD_TITLE_ART_H",
        "",
        "#include <stdint.h>",
        "",
        f"enum {{ LORD_TITLE_ART_WIDTH = {WIDTH},",
        f"       LORD_TITLE_ART_HEIGHT = {HEIGHT} }};",
        "",
        "static const uint16_t s_lord_title_art[",
        "    LORD_TITLE_ART_WIDTH * LORD_TITLE_ART_HEIGHT] = {",
    ]
    for start in range(0, len(values), 12):
        chunk = values[start : start + 12]
        lines.append("    " + ", ".join(f"UINT16_C(0x{value:04x})" for value in chunk) + ",")
    lines.extend(("};", "", "#endif", ""))
    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("preview", type=Path)
    parser.add_argument("header", type=Path)
    args = parser.parse_args()
    build(args.input, args.preview, args.header)


if __name__ == "__main__":
    main()
