#!/usr/bin/env node
// SPDX-License-Identifier: LicenseRef-LORD-Permission

/**
 * Import the immutable monster table from the authorized Synchronet LORD
 * source.  This is a development-time provenance tool; generated C has no
 * runtime dependency on Node.js or the upstream checkout.
 */

import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";

const EXPECTED_SHA256 =
  "a410a37e0b8e39a72cd8527fbbf37e48698cdeccdb7fa9f7ff296b25dfbec645";

if (process.argv.length !== 4) {
  console.error("usage: import_upstream_monsters.mjs LORD.JS OUTPUT.H");
  process.exit(2);
}

const sourcePath = process.argv[2];
const outputPath = process.argv[3];
const source = readFileSync(sourcePath, "utf8");
const digest = createHash("sha256").update(source).digest("hex");
if (digest !== EXPECTED_SHA256) {
  throw new Error(`upstream digest mismatch: ${digest}`);
}

const marker = "var monster_stats = ";
const start = source.indexOf(marker);
if (start < 0) {
  throw new Error("monster_stats marker is missing");
}
const arrayStart = start + marker.length;
const arrayEnd = source.indexOf("\n];", arrayStart);
if (arrayEnd < 0) {
  throw new Error("monster_stats terminator is missing");
}

// The pinned fragment is an array of data-only object literals.
const monsters = Function(
  `"use strict"; return (${source.slice(arrayStart, arrayEnd + 2)});`,
)();
if (!Array.isArray(monsters) || monsters.length !== 131) {
  throw new Error(`expected 131 monsters, found ${monsters.length}`);
}

// Preserve the authorized stats while adapting a few legacy descriptions for
// the kid-friendly Console OS edition. Keys are immutable upstream names so a
// source change cannot silently redirect an adaptation to another monster.
const KID_SAFE_MONSTERS = new Map([
  ["Rude Boy", { name: "Rude Rascal" }],
  ["Old Man", { name: "Wandering Elder" }],
  ["Wild Boar", { death: "The boar yields and runs into the brush." }],
  ["Ugly Old Hag", { name: "Forest Hag" }],
  ["Small Bear", { death: "The bear yields and lumbers safely away." }],
  ["Evil Wretch", { name: "Cranky Wanderer" }],
  ["Evil Wood Nymph", {
    weapon: "Puzzling Enchantment",
    death: "The nymph drops her spell and flees into the trees.",
  }],
  ["Huge Bald Man", {
    name: "Towering Traveler",
    death: "He yields and stomps away from the trail.",
  }],
  ["Muscled Midget", { name: "Muscled Sprinter", weapon: "Quick Jab" }],
  ["Lazy Bum", { name: "Sleepy Traveler" }],
  ["Red Neck", { name: "Country Trickster" }],
  ["Misfit The Ugly", { name: "Mischief Maker" }],
  ["Bald Medusa", { name: "Stone-Eyed Medusa" }],
  ["Gold Man", {
    death: "The Gold Man yields and drops a few ChompCoin.",
  }],
  ["Silent Death", { death: "The creature dissolves into harmless mist." }],
  ["Angry Liontaur", { death: "The liontaur bows and leaves the path." }],
  ["Werewolf", { death: "The werewolf howls and flees into the moonlight." }],
  ["Baby Dragon", { death: "The young dragon surrenders and flies home." }],
  ["Goblin Pygmy", { name: "Tiny Goblin" }],
  ["Apeman", { name: "Forest Ape" }],
  ["Sweet Looking Little Girl", { name: "Disguised Trickster" }],
  ["Apparently Weak Old Woman", { name: "Hooded Illusionist" }],
  ["The Screaming Eunich", {
    name: "The Screaming Herald",
    death: "The herald finally runs out of breath and yields.",
  }],
]);

function cString(value) {
  return `"${String(value)
    .replaceAll("\\", "\\\\")
    .replaceAll('"', '\\"')
    .replaceAll("\n", "\\n")}"`;
}

const lines = [
  "// SPDX-License-Identifier: LicenseRef-LORD-Permission",
  "// Generated by tools/import_upstream_monsters.mjs; do not hand-edit.",
  "// Synchronet sbbs commit 25232df05a8ba27a4dd9fcd38b4012c43660fb50",
  "// lord.js SHA-256 a410a37e0b8e39a72cd8527fbbf37e48698cdeccdb7fa9f7ff296b25dfbec645",
  "",
  "#ifndef P4_LORD_UPSTREAM_MONSTERS_H",
  "#define P4_LORD_UPSTREAM_MONSTERS_H",
  "",
  "enum { LORD_MONSTER_COUNT = 131 };",
  "",
  "static const lord_monster_t s_monsters[LORD_MONSTER_COUNT] = {",
];
for (const monster of monsters) {
  const adaptation = KID_SAFE_MONSTERS.get(monster.name) ?? {};
  const adapted = { ...monster, ...adaptation };
  adapted.death = adaptation.death ??
    `${adapted.name} yields and leaves the trail.`;
  for (const field of ["name", "weapon", "death"]) {
    if (typeof adapted[field] !== "string") {
      throw new Error(`monster ${field} is not text`);
    }
  }
  for (const field of ["str", "hp", "gold", "exp"]) {
    if (!Number.isInteger(monster[field]) || monster[field] < 0) {
      throw new Error(`monster ${field} is invalid`);
    }
  }
  lines.push(
    `    {${cString(adapted.name)}, ${cString(adapted.weapon)}, ` +
      `${cString(adapted.death)}, ${monster.str}, ${monster.hp}, ` +
      `${monster.gold}U, ${monster.exp}U},`,
  );
}
lines.push("};", "", "#endif", "");
writeFileSync(outputPath, lines.join("\n"));
