#!/usr/bin/env python3
"""Generate the bounded ASCII coverage atlas from the pinned Arimo font (OFL)."""
from pathlib import Path
import hashlib, json
from PIL import Image, ImageDraw, ImageFont
ROOT = Path(__file__).resolve().parents[3]
FONT = ROOT / 'third_party/arimo/Arimo.ttf'
source = json.loads((FONT.parent / 'source.json').read_text())
assert hashlib.sha256(FONT.read_bytes()).hexdigest() == source['files']['Arimo.ttf']['sha256']
font = ImageFont.truetype(str(FONT), 24)
font.set_variation_by_axes([600])
alpha = []
advance = []
for code in range(32, 127):
    im = Image.new('L', (24, 28))
    ImageDraw.Draw(im).text((0,22), chr(code), font=font, fill=255, anchor='ls')
    values = [min(15, (v + 8)//17) for v in im.getdata()]
    alpha += [(values[i]<<4) | values[i+1] for i in range(0,len(values),2)]
    advance.append(max(1,round(font.getlength(chr(code)))))
header = '// Generated by tools/generate_ui_font.py; Arimo coverage atlas, SIL OFL 1.1.\n// Source/license: third_party/arimo/. Do not edit by hand.\n#ifndef CONSOLE_UI_FONT_H\n#define CONSOLE_UI_FONT_H\n#include <stdint.h>\n'
header += 'static const uint8_t console_ui_font_advance[95] = {' + ','.join(map(str,advance)) + '};\n'
header += 'static const uint8_t console_ui_font_alpha[31920] = {\n'
header += '\n'.join(','.join(f'0x{v:02x}' for v in alpha[i:i+24])+',' for i in range(0,len(alpha),24))
header += '\n};\nstatic inline unsigned console_ui_glyph_alpha(unsigned char ch, unsigned x, unsigned y)\n{\n    if (ch < 32U || ch > 126U) ch = 63U;\n    const unsigned offset = ((unsigned)ch - 32U) * 672U + y * 24U + x;\n    const unsigned packed = console_ui_font_alpha[offset / 2U];\n    return offset % 2U == 0U ? packed >> 4U : packed & 15U;\n}\n#endif\n'
(ROOT/'components/console_shell/include/console/ui_font.h').write_text(header)
print('Generated 31,920-byte antialiased ASCII atlas')
