#!/usr/bin/env python3
"""Pack reviewed illustration assets and the pinned Arimo typeface for native UI."""
from pathlib import Path
import hashlib, json
from PIL import Image, ImageFont, ImageDraw
ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "components/console_shell/assets/nextgen"
OUT = ROOT / "components/console_shell/src/nextgen_assets.h"
manifest = json.loads((ASSETS / "source.json").read_text())
lines = ["/* Generated by tools/pack_nextgen.py. Source images and prompts: assets/nextgen/. */",
         "#ifndef CONSOLE_NEXTGEN_ASSETS_H", "#define CONSOLE_NEXTGEN_ASSETS_H", "#include <stdint.h>"]
for item in manifest["assets"]:
    source = ASSETS / (item["name"] + ".png")
    assert hashlib.sha256(source.read_bytes()).hexdigest() == item["sha256"]
    name = item["name"].replace("-", "_")
    size = (1024,576) if name == "byte_buddy" else (320,180)
    im = Image.open(source).convert("RGB").resize(size, Image.Resampling.LANCZOS)
    if name == "byte_buddy":
        indexed=im.quantize(colors=256,method=Image.Quantize.MEDIANCUT)
        palette=indexed.getpalette()
        values=[((palette[i]>>3)<<11)|((palette[i+1]>>2)<<5)|(palette[i+2]>>3) for i in range(0,768,3)]
        lines.append("static const uint16_t ng_art_byte_buddy_palette[256] = {")
        lines.extend(",".join(f"0x{v:04x}" for v in values[i:i+16])+"," for i in range(0,256,16))
        lines.append("};")
        indices=list(indexed.getdata())
        lines.append(f"static const uint8_t ng_art_byte_buddy[{len(indices)}] = {{")
        lines.extend(",".join(f"0x{v:02x}" for v in indices[i:i+24])+"," for i in range(0,len(indices),24))
        lines.append("};")
        continue
    values = [((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3) for r,g,b in im.getdata()]
    lines.append(f"static const uint16_t ng_art_{name}[{len(values)}] = {{")
    lines.extend(",".join(f"0x{v:04x}" for v in values[i:i+16])+"," for i in range(0,len(values),16))
    lines.append("};")
mark = Image.open(ROOT / "apps/console_os/main/assets/gamechangers_mark_v042.png").convert("RGBA").resize((64,64),Image.Resampling.LANCZOS)
mark_values=[]
for r,g,b,a in mark.getdata():
    v=((r>>3)<<11)|((g>>2)<<5)|(b>>3)
    mark_values.extend([v&255,v>>8,a])
lines.append("static const uint8_t ng_brand_mark[12288] = {")
lines.extend(",".join(f"0x{v:02x}" for v in mark_values[i:i+24])+"," for i in range(0,len(mark_values),24))
lines.append("};")
fontpath = ROOT / "third_party/arimo/Arimo.ttf"
source = json.loads((fontpath.parent / "source.json").read_text())
assert hashlib.sha256(fontpath.read_bytes()).hexdigest() == source["files"]["Arimo.ttf"]["sha256"]
for px,cell in [(32,40),(44,52),(68,80)]:
    font=ImageFont.truetype(str(fontpath),px);font.set_variation_by_axes([650])
    alpha=[];advance=[]
    for code in range(32,127):
        im=Image.new("L",(cell,cell));ImageDraw.Draw(im).text((1,round(px*0.97)),chr(code),font=font,fill=255,anchor="ls")
        vals=[min(15,(v+8)//17) for v in im.getdata()]
        alpha.extend((vals[i]<<4)|vals[i+1] for i in range(0,len(vals),2))
        advance.append(round(font.getlength(chr(code))))
    lines.append("/* Arimo, SIL OFL 1.1; license and exact source in third_party/arimo/. */")
    lines.append(f"static const uint8_t ng_font{px}_advance[95] = {{"+",".join(map(str,advance))+"};")
    lines.append(f"static const uint8_t ng_font{px}_alpha[{len(alpha)}] = {{")
    lines.extend(",".join(f"0x{v:02x}" for v in alpha[i:i+24])+"," for i in range(0,len(alpha),24))
    lines.append("};")
lines += ["#endif"]
OUT.write_text("\n".join(lines)+"\n")
print(f"Packed 4 artwork assets + 32/44/68px Arimo atlases: {OUT}")
