#!/usr/bin/env python3
"""Pack original built-in game covers; artwork stays outside Doom WAD data."""
from pathlib import Path
import hashlib, json, struct, importlib.util
from PIL import Image, ImageOps
ROOT = Path(__file__).resolve().parents[3]
ASSETS = ROOT / "components/console_shell/assets/game-covers"
OUT = ROOT / "components/console_shell/src/game_covers.inc"
spec = importlib.util.spec_from_file_location("pack_icon", ROOT / "scripts/pack-game-icon.py")
packer = importlib.util.module_from_spec(spec)
spec.loader.exec_module(packer)
lines = ["/* Generated by tools/pack_game_covers.py; original artwork and prompts in assets/game-covers/. */"]
def array(kind, name, values):
    lines.append(f"const {kind} {name}[{len(values)}] = {{")
    lines.extend(",".join(str(v) for v in values[i:i+24])+"," for i in range(0,len(values),24))
    lines.append("};")
for asset in json.loads((ASSETS/"source.json").read_text())["assets"]:
    if asset.get("editable_source"):
        editable = ASSETS / asset["editable_source"]
        assert hashlib.sha256(editable.read_bytes()).hexdigest() == asset["editable_source_sha256"]
    source = ASSETS / asset["source"]
    assert hashlib.sha256(source.read_bytes()).hexdigest() == asset["sha256"]
    name = asset["name"]
    im = ImageOps.fit(Image.open(source).convert("RGB"), (640,360), method=Image.Resampling.LANCZOS)
    indexed = im.quantize(colors=256, method=Image.Quantize.MEDIANCUT)
    palette = indexed.getpalette()
    palette += [0] * (768-len(palette))
    values = [((palette[i]>>3)<<11)|((palette[i+1]>>2)<<5)|(palette[i+2]>>3) for i in range(0,768,3)]
    array("uint16_t", f"console_{name}_cover_palette", values)
    array("uint8_t", f"console_{name}_cover_pixels", list(indexed.tobytes()))
    lines.append(f"const console_shell_artwork_t console_{name}_cover = {{ console_{name}_cover_pixels, console_{name}_cover_palette, 640, 360 }};")
    icon = packer.pack(source)
    array("uint16_t", f"console_{name}_icon_palette", struct.unpack("<256H", icon[16:528]))
    array("uint8_t", f"console_{name}_icon_pixels", list(icon[528:]))
# A legacy high-resolution hero is used only while its matching cartridge
# icon is installed. A newer cartridge icon must take precedence.
icon = packer.pack(ROOT / "components/console_shell/assets/nextgen/byte-buddy.png")
array("uint16_t", "console_byte_legacy_icon_palette", struct.unpack("<256H", icon[16:528]))
array("uint8_t", "console_byte_legacy_icon_pixels", list(icon[528:]))
OUT.write_text("\n".join(lines)+"\n")
print(OUT)
