#ifndef PLATFORM_BOARD_H
#define PLATFORM_BOARD_H

#if defined(ESP_PLATFORM)
/* Board selection is an ESP-IDF sdkconfig option.  Include it here so every
 * translation unit gets the same profile, including pure layout modules that
 * otherwise have no ESP-IDF headers of their own. */
#include "sdkconfig.h"
#endif

#if defined(CONFIG_PLATFORM_BOARD_TARGET_WAVESHARE_4_3)
/*
 * The ST7701 scanout remains at its proven native 480x800 timing. Games and
 * touch use an 800x480 landscape coordinate space; platform_display rotates
 * that logical surface clockwise into the native frame buffer.
 */
#define PLATFORM_BOARD_DISPLAY_WIDTH 800U
#define PLATFORM_BOARD_DISPLAY_HEIGHT 480U
#define PLATFORM_BOARD_DISPLAY_NATIVE_WIDTH 480U
#define PLATFORM_BOARD_DISPLAY_NATIVE_HEIGHT 800U
#define PLATFORM_BOARD_DISPLAY_ROTATION_CW_DEGREES 90U
#define PLATFORM_BOARD_DISPLAY_ORIENTATION_PORTRAIT 0
#define PLATFORM_BOARD_LCD_BACKLIGHT_GPIO 26
#define PLATFORM_BOARD_LCD_RESET_GPIO 27
#define PLATFORM_BOARD_TOUCH_RESET_GPIO 23
#define PLATFORM_BOARD_TOUCH_INTERRUPT_GPIO (-1)
#define PLATFORM_BOARD_I2C_SDA_GPIO 7
#define PLATFORM_BOARD_I2C_SCL_GPIO 8
#define PLATFORM_BOARD_I2C_PORT 1
#define PLATFORM_BOARD_AUDIO_MCLK_GPIO 13
#define PLATFORM_BOARD_AUDIO_BCLK_GPIO 12
#define PLATFORM_BOARD_AUDIO_LRCLK_GPIO 10
#define PLATFORM_BOARD_AUDIO_DOUT_GPIO 9
#define PLATFORM_BOARD_AUDIO_DIN_GPIO 11
#define PLATFORM_BOARD_AUDIO_AMP_GPIO 53
#define PLATFORM_BOARD_USB_DATA_N_GPIO 24
#define PLATFORM_BOARD_USB_DATA_P_GPIO 25
#define PLATFORM_BOARD_USB_VBUS_PRESENT 1
#define PLATFORM_BOARD_USB_HOST_SOURCE_AUTHORIZED 0
#define PLATFORM_BOARD_SDMMC_CLK_GPIO 43
#define PLATFORM_BOARD_SDMMC_CMD_GPIO 44
#define PLATFORM_BOARD_SDMMC_D0_GPIO 39
#define PLATFORM_BOARD_SDMMC_POWER_LDO_CHANNEL 4
#else
#define PLATFORM_BOARD_DISPLAY_WIDTH 1024U
#define PLATFORM_BOARD_DISPLAY_HEIGHT 600U
#define PLATFORM_BOARD_DISPLAY_NATIVE_WIDTH 1024U
#define PLATFORM_BOARD_DISPLAY_NATIVE_HEIGHT 600U
#define PLATFORM_BOARD_DISPLAY_ROTATION_CW_DEGREES 0U
#define PLATFORM_BOARD_DISPLAY_ORIENTATION_PORTRAIT 0
#define PLATFORM_BOARD_LCD_BACKLIGHT_GPIO 31
#define PLATFORM_BOARD_LCD_RESET_GPIO (-1)
#define PLATFORM_BOARD_TOUCH_RESET_GPIO 40
#define PLATFORM_BOARD_TOUCH_INTERRUPT_GPIO 42
#define PLATFORM_BOARD_I2C_SDA_GPIO 45
#define PLATFORM_BOARD_I2C_SCL_GPIO 46
#define PLATFORM_BOARD_I2C_PORT 1
#define PLATFORM_BOARD_AUDIO_MCLK_GPIO 24
#define PLATFORM_BOARD_AUDIO_BCLK_GPIO 22
#define PLATFORM_BOARD_AUDIO_LRCLK_GPIO 21
#define PLATFORM_BOARD_AUDIO_DOUT_GPIO 23
#define PLATFORM_BOARD_AUDIO_DIN_GPIO (-1)
#define PLATFORM_BOARD_AUDIO_AMP_GPIO 30
#define PLATFORM_BOARD_USB_DATA_N_GPIO (-1)
#define PLATFORM_BOARD_USB_DATA_P_GPIO (-1)
#define PLATFORM_BOARD_USB_VBUS_PRESENT 0
#define PLATFORM_BOARD_USB_HOST_SOURCE_AUTHORIZED 0
/* Scoped 1-bit path authorized by the recorded Elecrow storage evidence. */
#define PLATFORM_BOARD_SDMMC_CLK_GPIO 43
#define PLATFORM_BOARD_SDMMC_CMD_GPIO 44
#define PLATFORM_BOARD_SDMMC_D0_GPIO 39
#define PLATFORM_BOARD_SDMMC_POWER_LDO_CHANNEL (-1)
#endif

/*
 * Every Console OS screen and game renders through the same 320x200 surface.
 * Fit that surface to the selected board with the largest centered viewport
 * that preserves its 8:5 aspect ratio. This deliberately permits fractional
 * nearest-neighbor scaling: the Waveshare target becomes 768x480 instead of
 * being limited to the much smaller integer-2x 640x400 viewport.
 */
#define PLATFORM_BOARD_GAME_SURFACE_WIDTH 320U
#define PLATFORM_BOARD_GAME_SURFACE_HEIGHT 200U
#if (PLATFORM_BOARD_DISPLAY_WIDTH * PLATFORM_BOARD_GAME_SURFACE_HEIGHT) <= \
    (PLATFORM_BOARD_DISPLAY_HEIGHT * PLATFORM_BOARD_GAME_SURFACE_WIDTH)
#define PLATFORM_BOARD_GAME_VIEWPORT_WIDTH PLATFORM_BOARD_DISPLAY_WIDTH
#define PLATFORM_BOARD_GAME_VIEWPORT_HEIGHT \
    ((PLATFORM_BOARD_DISPLAY_WIDTH * PLATFORM_BOARD_GAME_SURFACE_HEIGHT) / \
     PLATFORM_BOARD_GAME_SURFACE_WIDTH)
#else
#define PLATFORM_BOARD_GAME_VIEWPORT_WIDTH \
    ((PLATFORM_BOARD_DISPLAY_HEIGHT * PLATFORM_BOARD_GAME_SURFACE_WIDTH) / \
     PLATFORM_BOARD_GAME_SURFACE_HEIGHT)
#define PLATFORM_BOARD_GAME_VIEWPORT_HEIGHT PLATFORM_BOARD_DISPLAY_HEIGHT
#endif
#define PLATFORM_BOARD_GAME_MARGIN_LEFT \
    ((PLATFORM_BOARD_DISPLAY_WIDTH - PLATFORM_BOARD_GAME_VIEWPORT_WIDTH) / 2U)
#define PLATFORM_BOARD_GAME_MARGIN_RIGHT \
    (PLATFORM_BOARD_DISPLAY_WIDTH - PLATFORM_BOARD_GAME_VIEWPORT_WIDTH - \
     PLATFORM_BOARD_GAME_MARGIN_LEFT)
#define PLATFORM_BOARD_GAME_MARGIN_TOP \
    ((PLATFORM_BOARD_DISPLAY_HEIGHT - PLATFORM_BOARD_GAME_VIEWPORT_HEIGHT) / 2U)
#define PLATFORM_BOARD_GAME_MARGIN_BOTTOM \
    (PLATFORM_BOARD_DISPLAY_HEIGHT - PLATFORM_BOARD_GAME_VIEWPORT_HEIGHT - \
     PLATFORM_BOARD_GAME_MARGIN_TOP)

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    PLATFORM_BOARD_ELECROW_10_1 = 0,
    PLATFORM_BOARD_WAVESHARE_4_3,
} platform_board_kind_t;

platform_board_kind_t platform_board_kind(void);
const char *platform_board_name(void);

#ifdef __cplusplus
}
#endif

#endif
