#!/usr/bin/env python3
"""Convert the reviewed ImageGen rink into a fixed 320x200 RGB565 include."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image

WIDTH = 320
HEIGHT = 200


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    with Image.open(args.input) as source:
        image = source.convert("RGB")
        if abs(image.width * HEIGHT - image.height * WIDTH) > image.height:
            raise SystemExit("source must have an approximately 16:10 aspect ratio")
        image = image.resize((WIDTH, HEIGHT), Image.Resampling.LANCZOS)

    pixels = image.load()
    if pixels is None:
        raise SystemExit("source image could not be decoded")
    values = [
        rgb565(*pixels[x, y])
        for y in range(HEIGHT)
        for x in range(WIDTH)
    ]
    lines = [
        "// Generated by tools/png_to_rink.py; do not edit by hand.",
        f"enum {{ P4_AIR_HOCKEY_RINK_WIDTH = {WIDTH},",
        f"       P4_AIR_HOCKEY_RINK_HEIGHT = {HEIGHT} }};",
        "static const uint16_t p4_air_hockey_rink_rgb565[] = {",
    ]
    for offset in range(0, len(values), 12):
        row = ", ".join(f"UINT16_C(0x{value:04x})"
                        for value in values[offset:offset + 12])
        lines.append(f"    {row},")
    lines.append("};")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
