#!/usr/bin/env python3
"""Convert the reviewed ImageGen object sheet into keyed RGB565 sprites."""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image

TRANSPARENT_KEY = 0x07E0
ICE_BACKGROUND = (6, 64, 108)
OBJECTS = (
    ("local_striker", 27),
    ("rival_striker", 27),
    ("puck", 17),
)


def rgb565(red: int, green: int, blue: int) -> int:
    value = ((red >> 3) << 11) | ((green >> 2) << 5) | (blue >> 3)
    return value ^ 1 if value == TRANSPARENT_KEY else value


def fit_object(segment: Image.Image, size: int) -> Image.Image:
    alpha = segment.getchannel("A")
    bounds = alpha.getbbox()
    if bounds is None:
        raise SystemExit("sprite segment is empty")
    cropped = segment.crop(bounds)
    side = max(cropped.width, cropped.height)
    padded = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    padded.alpha_composite(
        cropped, ((side - cropped.width) // 2, (side - cropped.height) // 2)
    )
    return padded.resize((size, size), Image.Resampling.LANCZOS)


def encode_sprite(image: Image.Image) -> list[int]:
    values: list[int] = []
    pixels = image.load()
    if pixels is None:
        raise SystemExit("sprite could not be decoded")
    for y in range(image.height):
        for x in range(image.width):
            red, green, blue, alpha = pixels[x, y]
            if alpha <= 8:
                values.append(TRANSPARENT_KEY)
                continue
            inverse = 255 - alpha
            values.append(rgb565(
                (red * alpha + ICE_BACKGROUND[0] * inverse) // 255,
                (green * alpha + ICE_BACKGROUND[1] * inverse) // 255,
                (blue * alpha + ICE_BACKGROUND[2] * inverse) // 255,
            ))
    return values


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    with Image.open(args.input) as source_image:
        source = source_image.convert("RGBA")
        if source.width % len(OBJECTS) != 0:
            raise SystemExit("sprite sheet width must split into three columns")
        column_width = source.width // len(OBJECTS)
        sprites = []
        for index, (name, size) in enumerate(OBJECTS):
            segment = source.crop((index * column_width, 0,
                                   (index + 1) * column_width, source.height))
            sprites.append((name, size, encode_sprite(fit_object(segment, size))))

    lines = [
        "// Generated by tools/png_to_objects.py; do not edit by hand.",
        f"enum {{ P4_AIR_HOCKEY_OBJECT_TRANSPARENT_KEY = 0x{TRANSPARENT_KEY:04x} }};",
    ]
    for name, size, values in sprites:
        upper = name.upper()
        lines.extend((
            f"enum {{ P4_AIR_HOCKEY_{upper}_WIDTH = {size},",
            f"       P4_AIR_HOCKEY_{upper}_HEIGHT = {size} }};",
            f"static const uint16_t p4_air_hockey_{name}_rgb565[] = {{",
        ))
        for offset in range(0, len(values), 12):
            row = ", ".join(
                f"UINT16_C(0x{value:04x})" for value in values[offset:offset + 12]
            )
            lines.append(f"    {row},")
        lines.append("};")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
