#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Bake the unchanged integer sphere lighting, not new artwork, to RGB565 LUTs."""
from pathlib import Path

def div(a,b):
    return (abs(a)//abs(b))*(-1 if (a<0)!=(b<0) else 1)

def rgb(r,g,b):
    return (r>>3)<<11 | (g>>2)<<5 | b>>3

def main():
    values=[];offsets=[0]*15
    for radius in range(3,15):
        offsets[radius]=len(values)
        for player in range(2):
            for stripe in range(2):
                for dy in range(-radius,radius+1):
                    for dx in range(-radius,radius+1):
                        d=dx*dx+dy*dy
                        light=max(35,min(245,176-div(d*100,radius*radius)-div((dx+dy)*34,radius)))
                        r=light if player else div(light*3,4)
                        g=div(light*3,5) if player else light
                        b=div(light,3) if player else min(255,light+30)
                        if stripe:r,g,b=div(r*4,5),div(g*4,5),div(b*4,5)
                        values.append(rgb(r,g,b) if d<=radius*radius else 0)
    out='// SPDX-License-Identifier: MIT\n// Generated by tools/compile_marble_lighting.py; exact original sphere shading.\n'
    out+='static const uint16_t tm_marble_offsets[15]={'+','.join(map(str,offsets))+'};\n'
    out+='static const uint16_t tm_marble_lighting[]={\n'
    out+=''.join(','.join(f'0x{v:04x}' for v in values[i:i+16])+',\n' for i in range(0,len(values),16))+'};\n'
    target=Path(__file__).resolve().parents[1]/'src/generated/marble_lighting.inc'
    target.write_text(out)
    print(f'{len(values)*2} lighting bytes; radii3..14, two players, normal/stripe colors')
if __name__=='__main__':main()
