#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Bake unchanged fixed-grid projection constants with C integer truncation."""
from pathlib import Path


def div(a, b):
    return (abs(a) // abs(b)) * (-1 if (a < 0) != (b < 0) else 1)


def main():
    vertices = []
    for y in range(19):
        row = []
        for x in range(31):
            xc = (x * 8 - 120) * 256
            yy = y * 8 * 256
            depth = 600 - div(yy, 256) - div(xc, 10 * 256)
            sx = 156 * 256 + div(xc * 530 + (yy - 72 * 256) * 60, depth)
            row.append((yy * 330 + xc * 45, depth,
                        div(sx * 768, 320 * 256), div(sx * 320, 320 * 256)))
        vertices.append(row)
    out = ('// SPDX-License-Identifier: MIT\n'
           '// Generated by tools/compile_water_projection.py; exact fixed grid.\n'
           'static const tm_water_projection_vertex tm_water_projection[TM_H+1][TM_W+1]={\n')
    for row in vertices:
        out += ' {' + ','.join('{' + ','.join(map(str, v)) + '}' for v in row) + '},\n'
    out += '};\n'
    target = Path(__file__).resolve().parents[1] / 'src/generated/water_projection.inc'
    target.write_text(out)
    print('589 cached water vertices; depth and native/legacy x, original y numerator')


if __name__ == '__main__':
    main()
