#!/usr/bin/env python3
"""Measured-cell conversion of the original directional chomp/spirit atlas."""
from PIL import Image
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[1]
im=Image.open(ROOT/'assets/chase_characters_v3.png').convert('RGBA')
rows=[0,250,480,715,990,1246,1536]
frames=[];bounds=[];source_crops=[]
for row in range(6):
 for col in range(4):
  box=(col*256,rows[row],(col+1)*256,rows[row+1]);crop=im.crop(box)
  bb=crop.getchannel('A').point(lambda a:255 if a>=160 else 0).getbbox()
  if bb is None:raise ValueError('empty cell')
  bounds.append([box[0]+bb[0],box[1]+bb[1],box[0]+bb[2],box[1]+bb[3]])
  crop=crop.crop(bb);source_crops.append(crop.copy());crop.thumbnail((44,44),Image.Resampling.LANCZOS)
  frame=Image.new('RGBA',(48,48));frame.paste(crop,((48-crop.width)//2,(48-crop.height)//2));frames.append(frame)
hero=source_crops[8].copy();hero.thumbnail((128,128),Image.Resampling.LANCZOS)
hero_frame=Image.new('RGBA',(128,128));hero_frame.paste(hero,((128-hero.width)//2,(128-hero.height)//2))
def values(im):
 return [0 if a<160 else max(1,((r>>3)<<11)|((g>>2)<<5)|(b>>3)) for r,g,b,a in im.getdata()]
lines=['/* Generated by tools/convert_chase.py; original ImageGen art. */','static const uint16_t chase_art[24][48*48] = {']
for im in frames:
 vals=values(im);lines.append('{')
 for i in range(0,len(vals),16):lines.append(','.join(f'0x{v:04x}' for v in vals[i:i+16])+',')
 lines.append('},')
lines.extend(['};','static const uint16_t chase_hero[128*128] = {'])
vals=values(hero_frame)
for i in range(0,len(vals),16):lines.append(','.join(f'0x{v:04x}' for v in vals[i:i+16])+',')
lines.append('};');(ROOT/'src/generated/chase_art.inc').write_text('\n'.join(lines)+'\n')
preview=Image.new('RGBA',(48*4,48*6))
for i,f in enumerate(frames):preview.paste(f,((i%4)*48,(i//4)*48))
preview.save(ROOT/'assets/chase_compiled_preview.png');hero_frame.save(ROOT/'assets/chase_hero_preview.png')
p=ROOT/'assets/chase_provenance.json';d=json.loads(p.read_text());d['conversion']={'row_boundaries':rows,'measured_opaque_bounds':bounds,'sampling':'Lanczos reduction, preserve aspect, 2-pixel cell margin; alpha >=160, RGB565 chroma key 0','cell_size':[48,48],'sprite_static_bytes':24*48*48*2,'title_hero_cell':8,'title_hero_size':[128,128],'hero_static_bytes':128*128*2,'total_static_bytes':24*48*48*2+128*128*2};p.write_text(json.dumps(d,indent=2)+'\n')
print('Original chomp and spirit atlas:',d['conversion']['total_static_bytes'],'bytes')
