#!/usr/bin/env python3
"""Pack exact native/fallback scenery rows exported by render_backdrop."""
import argparse
import struct
from pathlib import Path
p=argparse.ArgumentParser(description=__doc__)
p.add_argument("prefix",type=Path)
p.add_argument("output",type=Path)
a=p.parse_args()
runs=[]
rows={}
lookup={}
for width,height in ((320,200),(768,480)):
    images=[]
    for clear in (0,1):
        data=Path(f"{a.prefix}-{width}-{clear}.rgb565").read_bytes()
        assert len(data)==width*height*2
        images.append(struct.unpack(f"<{width*height}H",data))
    assert all((0xffb2 if x==0x4e5e else x)==y for x,y in zip(*images)), "clear palette mismatch"
    offsets=[]
    for y in range(height):
        row=images[0][y*width:(y+1)*width]
        if row not in lookup:
            lookup[row]=len(runs)
            x=0
            while x<width:
                end=x+1
                while end<width and row[end]==row[x]:end+=1
                runs.append(((end-x)<<16)|row[x])
                x=end
        offsets.append(lookup[row])
    rows[width]=offsets
lines=["// SPDX-License-Identifier: MIT", "// Generated by tools/render_backdrop.c + tools/pack_backdrop.py; do not edit."]
for name,values in [("maze_backdrop_runs",runs)]+[(f"maze_backdrop_rows_{w}",v) for w,v in rows.items()]:
    lines.append(f"static const uint32_t {name}[{len(values)}]={{")
    for i in range(0,len(values),8):lines.append("    "+",".join(f"0x{v:08x}U" for v in values[i:i+8])+",")
    lines.append("};")
a.output.write_text("\n".join(lines)+"\n")
print(f"Backdrop: {len(lookup)} unique rows; {(len(runs)+sum(map(len,rows.values())))*4} bytes; no runtime cache")
