// SPDX-License-Identifier: MIT
/* Generated by scripts/doom/arena-content.py from third_party/game-data.json. */
#ifndef P4_DOOM_ARENA_CONTENT_H
#define P4_DOOM_ARENA_CONTENT_H
#define P4_GCA_CONTENT_SHA256 {0x36,0x3c,0x69,0xfd,0x5b,0x0a,0xe3,0xfa,0xa5,0x36,0x0d,0x96,0x62,0x44,0x14,0xe6,0xda,0xbd,0x2d,0x4c,0x9c,0x86,0xd1,0xea,0xb5,0x18,0x89,0x9d,0x80,0x95,0x35,0x8b}
#define P4_GCA_CONTENT_FILES(X) \
    X(5, BASE, "", "FREEDOOM2.WAD", 28787748, "a8772e088847032510d97ba2312406a6998f21cbab44d4ff10696faa9c0ecd4b") \
    X(6, PWAD, "", "PUREHADES.WAD", 2313392, "ab027fbeebe20787214a3bc1239bba73271030dc284cd108c20ae8bc73752fc8") \
    X(13, DWANGO, "", "DWANGO5.WAD", 2109396, "2b7658f126321fc2ccf953dbbe8d585b4162350080b9715b46fc617d32cdb13a") \
    X(7, COPYING, "/GCADOOM/licenses", "Freedoom-0.13.0-COPYING.txt", 1644, "7c62f2c520769c798774f416637eec4921e5f0aafdac1245ae7c8a8cf65fe102") \
    X(8, CREDITS_MUSIC, "/GCADOOM/licenses", "Freedoom-0.13.0-CREDITS-MUSIC.txt", 9388, "2bb77677bbc4e587bba44ccb6514ee0f5397c7bb8ae9580b9188d3d6a57c0a31") \
    X(9, CREDITS, "/GCADOOM/licenses", "Freedoom-0.13.0-CREDITS.txt", 15872, "72364333d295c598d75ef9553d3b3661ad0b60e27271c87b7637c74b2f46918a") \
    X(10, README, "/GCADOOM", "README.md", 8324, "09cedf54ba776413fcee13aee95563eb988bc71887a564e28bf909187b23a55c") \
    X(11, MANIFEST, "/GCADOOM", "manifest.json", 15101, "1344d73da9c7f1f264e817d50a5747a2b3fe3b7dfe584f21d5f59b9231733712") \
    X(12, TRACKLIST, "/GCADOOM/music", "tracklist.json", 5577, "e8d930a8528a48d07b3460feb7eac0a295101b7c042e1a53dc678fb52e3582d2") \
    X(16, LICENSE, "/GCADOOM", "LICENSE", 1375, "889d96b2da176a6242b47cd3375cadb20d4dd9f16d06d98763b647e9b33ef511") \
    X(17, HADES_CREDITS, "/GCADOOM", "CREDITS.md", 2366, "906c8a6ab2c664c2a57f117cbb79af2c6ae00da50c53fe6dd70d7ec36a1bde26") \
    X(18, CC_BY_SA, "/GCADOOM/licenses", "CC-BY-SA-4.0.txt", 20138, "28a9529c7d0bb4dc51f4bf5c116a3d16ef247a052f7591466768ddf563fd1cf5") \
    X(19, MIDI_NOTICE, "/GCADOOM/licenses", "Ultimate-MIDI-Pack-original-readme.txt", 14450, "37c32dcaca6f8eb143842c7cdf2bce06865c13fe6207094d092ea0c94a313456") \
    X(20, MIT, "/GCADOOM/licenses", "MIT.txt", 1068, "ddba3b25d16067476f8e4a4498c3f9f43328d22d30b5f1019cd73b0e07f5f3e5") \
    X(14, DWANGO_NOTICE, "/GCADOOM", "DWANGO5.TXT", 2234, "bfb0a573af27da78ac853deedd7754c73e53f472798f5f129500eedbef856cf1") \
    X(15, DWANGO_DIZ, "/GCADOOM", "FILE_ID.DIZ", 210, "faaa4a0867d05ea49114b9e05ddad783062b9ddba64f8716d5f2556d63aac485")
enum {
#define P4_GCA_ENUM(kind, symbol, dir, name, size, hash) P4_GCA_##symbol,
    P4_GCA_CONTENT_FILES(P4_GCA_ENUM)
#undef P4_GCA_ENUM
    P4_GCA_FILE_COUNT
};
#endif
