// SPDX-License-Identifier: MIT
/* Generated by scripts/doom/arena-content.py from third_party/game-data.json. */
#ifndef P4_DOOM_ARENA_CONTENT_H
#define P4_DOOM_ARENA_CONTENT_H
#define P4_GCA_CONTENT_SHA256 {0x6f,0xbd,0xec,0x7a,0x25,0xf8,0x70,0x88,0x88,0x43,0x82,0x70,0x6f,0xbe,0x2c,0x73,0xdb,0xa2,0x84,0xc3,0x13,0x9e,0xe0,0x4f,0x11,0x13,0xd7,0xfb,0x7b,0xba,0x39,0x60}
#define P4_GCA_CONTENT_FILES(X) \
    X(5, BASE, "", "FREEDOOM2.WAD", 28787748, "a8772e088847032510d97ba2312406a6998f21cbab44d4ff10696faa9c0ecd4b") \
    X(6, PWAD, "", "PUREHELL.WAD", 875026, "b0e8ab211fe263bdf263b219cd0f3584cac0071ec1cf3ce73defa843f00a3663") \
    X(13, DWANGO, "", "DWANGO5.WAD", 2109396, "2b7658f126321fc2ccf953dbbe8d585b4162350080b9715b46fc617d32cdb13a") \
    X(7, COPYING, "/GCADOOM", "Freedoom-0.13.0-COPYING.txt", 1644, "7c62f2c520769c798774f416637eec4921e5f0aafdac1245ae7c8a8cf65fe102") \
    X(8, CREDITS_MUSIC, "/GCADOOM", "Freedoom-0.13.0-CREDITS-MUSIC.txt", 9388, "2bb77677bbc4e587bba44ccb6514ee0f5397c7bb8ae9580b9188d3d6a57c0a31") \
    X(9, CREDITS, "/GCADOOM", "Freedoom-0.13.0-CREDITS.txt", 15872, "72364333d295c598d75ef9553d3b3661ad0b60e27271c87b7637c74b2f46918a") \
    X(10, README, "/GCADOOM", "README.txt", 4220, "e10bcbce5d602672fd7dcac442861d9675db902c3669fb7b9510062def04832d") \
    X(11, MANIFEST, "/GCADOOM", "build-manifest.json", 2823, "90b9629971c5af62a7aa2406727c2153ebaca567a3b0fbcd002e8115f8c8c721") \
    X(12, MIDI, "/GCADOOM", "Beasts-of-Horizon.mid", 43798, "01c7618d0e03224156f29cdb07895ca224f0a30ba41fe67595fffadf0454fa89") \
    X(14, DWANGO_NOTICE, "/GCADOOM", "DWANGO5.TXT", 2234, "bfb0a573af27da78ac853deedd7754c73e53f472798f5f129500eedbef856cf1") \
    X(15, DWANGO_DIZ, "/GCADOOM", "FILE_ID.DIZ", 210, "faaa4a0867d05ea49114b9e05ddad783062b9ddba64f8716d5f2556d63aac485")
enum {
#define P4_GCA_ENUM(kind, symbol, dir, name, size, hash) P4_GCA_##symbol,
    P4_GCA_CONTENT_FILES(P4_GCA_ENUM)
#undef P4_GCA_ENUM
    P4_GCA_FILE_COUNT
};
#endif
