#!/usr/bin/env python3
"""Offline launch artwork: bounded native indexed RGB565, no runtime decoder."""
from pathlib import Path
import hashlib
import importlib.util
import json
from PIL import Image, ImageOps

GAME = Path(__file__).resolve().parents[1]
ROOT = GAME.parents[1]
ART = GAME / "assets/launch-v5"
OUTPUT = GAME / "src/generated/byte_buddy_city.inc"


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main():
    source = Image.open(ART / "city-source.png").convert("RGB")
    native = ImageOps.fit(source, (768, 268), method=Image.Resampling.LANCZOS)
    indexed = native.quantize(colors=256, method=Image.Quantize.MEDIANCUT,
                              dither=Image.Dither.NONE)
    palette = indexed.getpalette()
    colors = [((palette[i] >> 3) << 11) | ((palette[i+1] >> 2) << 5) |
              (palette[i+2] >> 3) for i in range(0, 768, 3)]
    lines = ["// SPDX-License-Identifier: MIT",
             "// Generated by tools/pack_launch_art.py; 768x268 native indexed RGB565.",
             "static const uint16_t bb_city_palette[256] = {"]
    for start in range(0, 256, 16):
        lines.append("    " + ",".join(f"0x{c:04x}" for c in colors[start:start+16]) + ",")
    lines += ["};", "static const uint16_t bb_city_dim_palette[256] = {"]
    dim = [(((c >> 11) * 3 // 5) << 11) | ((((c >> 5) & 63) * 3 // 5) << 5) | ((c & 31) * 3 // 5) for c in colors]
    for start in range(0, 256, 16):
        lines.append("    " + ",".join(f"0x{c:04x}" for c in dim[start:start+16]) + ",")
    lines += ["};", "static const uint8_t bb_city_indices[768 * 268] = {"]
    pixels = indexed.tobytes()
    for start in range(0, len(pixels), 32):
        lines.append("    " + ",".join(str(v) for v in pixels[start:start+32]) + ",")
    lines += ["};", ""]
    OUTPUT.write_text("\n".join(lines))
    spec = importlib.util.spec_from_file_location("pack_game_icon", ROOT / "scripts/pack-game-icon.py")
    packer = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(packer)
    (ART / "launcher.p4i").write_bytes(packer.pack(ART / "dragon-cover-source.png"))
    provenance_path = ART / "provenance.json"
    provenance = json.loads(provenance_path.read_text())
    for entry in provenance["sources"]:
        entry["sha256"] = sha(ART / entry["path"])
    provenance["conversion"] = {
        "tool": "games/byte_buddy/tools/pack_launch_art.py",
        "city": "Center-fit 768x268 Lanczos; Pillow median-cut 256 colors, no dithering; RGB565 palette + byte indices; opaque",
        "city_static_bytes": len(pixels) + 1024,
        "city_include_sha256": sha(OUTPUT),
        "icon": "Shared pack-game-icon.py: center-fit 128x72 Lanczos, 256 RGB565 colors, opaque P4ICON1",
        "icon_bytes": (ART / "launcher.p4i").stat().st_size,
        "icon_sha256": sha(ART / "launcher.p4i"),
        "pillow_version": Image.__version__,
    }
    provenance_path.write_text(json.dumps(provenance, indent=2) + "\n")
    print(json.dumps(provenance["conversion"], indent=2))


if __name__ == "__main__":
    main()
