#!/usr/bin/env python3
"""Reproduce the flight boot sprite and pinned Arimo font atlases."""
from pathlib import Path
import hashlib, json
from PIL import Image, ImageFont, ImageDraw
ROOT=Path(__file__).resolve().parents[3]
assets=ROOT/"apps/console_os/main/assets"
meta=json.loads((assets/"gamechangers_mark_flight.json").read_text())
src=assets/"gamechangers_mark_flight.png"
assert hashlib.sha256(src.read_bytes()).hexdigest()==meta["source_sha256"]
im=Image.open(src).convert("RGBA").resize((384,384),Image.Resampling.LANCZOS)
packed=bytearray()
for r,g,b,a in im.getdata():
    v=((r>>3)<<11)|((g>>2)<<5)|(b>>3);packed.extend((v&255,v>>8,a))
assert hashlib.sha256(packed).hexdigest()==meta["packed_sha256"]
(assets/"gamechangers_mark_flight.rgb565a8").write_bytes(packed)
fontpath=ROOT/"third_party/arimo/Arimo.ttf"
fontmeta=json.loads(fontpath.with_name("source.json").read_text())
assert hashlib.sha256(fontpath.read_bytes()).hexdigest()==fontmeta["files"]["Arimo.ttf"]["sha256"]
lines=["/* Generated by pack_flight_assets.py. Arimo: SIL OFL 1.1, third_party/arimo/. */","#include <stdint.h>"]
for px,cell,chars in [(32,40,"".join(chr(i) for i in range(32,127))),(56,64,"".join(sorted(set("GameChangersAI"))))]:
    font=ImageFont.truetype(str(fontpath),px);font.set_variation_by_axes([650])
    alpha=[];advance=[]
    for c in chars:
        im=Image.new("L",(cell,cell));ImageDraw.Draw(im).text((0,round(px*.97)),c,font=font,fill=255,anchor="ls")
        values=[min(15,(v+8)//17) for v in im.getdata()]
        alpha.extend((values[i]<<4)|values[i+1] for i in range(0,len(values),2))
        advance.append(round(font.getlength(c)))
    lines.append(f"static const char flight_font{px}_chars[] = "+json.dumps(chars)+";")
    lines.append(f"static const uint8_t flight_font{px}_advance[] = {{"+",".join(map(str,advance))+"};")
    lines.append(f"static const uint8_t flight_font{px}_alpha[] = {{")
    lines.extend(",".join(f"0x{v:02x}" for v in alpha[i:i+24])+"," for i in range(0,len(alpha),24))
    lines.append("};")
(ROOT/"components/console_startup/src/flight_fonts.h").write_text("\n".join(lines)+"\n")
print("Boot sprite and native 32/56px font atlases verified and packed.")
