#!/usr/bin/env python3
"""Compile ImageGen table material to bounded RGB565; Pillow is build-time only."""
from pathlib import Path
from PIL import Image
import json
root = Path(__file__).resolve().parents[1]
meta = json.loads((root / 'assets/table-materials-provenance.json').read_text())
image = Image.open(root / 'assets/table-materials-imagegen.png').convert('RGB')
assert image.size == (1254, 1254), image.size
parts = [('card_table_felt', meta['felt_quadrant'], 128)]
if meta['include_back']:
    parts.append(('card_table_back', meta['back_quadrant'], 96))
output = ['// SPDX-License-Identifier: MIT', '// Generated by tools/convert_table_materials.py. Do not edit.']
for name, quadrant, side in parts:
    col, row = quadrant % 2, quadrant // 2
    crop = image.crop((col * 627, row * 627, (col + 1) * 627, (row + 1) * 627))
    # Material illustration (not pixel art): area filtering prevents aliasing in fine fibers.
    crop = crop.resize((side, side), Image.Resampling.BOX)
    values = [(r >> 3) << 11 | (g >> 2) << 5 | b >> 3 for r,g,b in crop.getdata()]
    output += [f'static const uint16_t {name}[{side}U * {side}U] = {{']
    for offset in range(0,len(values),12):
        output += ['    ' + ','.join(f'0x{v:04x}' for v in values[offset:offset+12]) + ',']
    output += ['};']
(root / 'src/generated/table_materials.inc').write_text('\n'.join(output)+'\n')
