#!/usr/bin/env python3
"""Convert the checked-in CC0 Kenney dice recordings to bounded PCM clips.
Requires ffmpeg and NumPy. The original recordings and license are preserved.
"""
from pathlib import Path
import hashlib,json,subprocess
import numpy as np
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'apps/dice_core2/assets'; RATE=22050
clips=[];records=[]
for kind in ('shake','throw'):
    for i in range(1,4):
        src=OUT/'kenney'/f'dice-{kind}-{i}.ogg'
        pcm=subprocess.run(['ffmpeg','-v','error','-i',str(src),'-ac','1','-ar',str(RATE),'-af','highpass=f=120','-f','s16le','-'],capture_output=True,check=True).stdout
        x=np.frombuffer(pcm,dtype='<i2').astype(float)
        segments=[]
        if kind=='shake':
            width=int(.235*RATE)
            # Put the strongest recorded contact 35 ms after the motor
            # command, allowing the ERM to spin up before the sound hits.
            for lo,hi in ((.12,.60),(.72,1.10)):
                lo_sample=int(lo*RATE);hi_sample=min(int(hi*RATE),len(x)-width)
                peak=lo_sample+int(np.argmax(abs(x[lo_sample:hi_sample])))
                start=max(0,peak-int(.035*RATE))
                segments.append((start,x[start:start+width].copy()))
        else:
            active=np.flatnonzero(abs(x)>max(100,abs(x).max()*.015))
            a=max(0,int(active[0])-100);b=min(len(x),int(active[-1])+220)
            segments.append((a,np.concatenate([np.zeros(int(.035*RATE)),x[a:b]])))
        for start,y in segments:
            y*=26000/max(1,abs(y).max())
            fade=min(110,len(y)//4);y[:fade]*=np.linspace(0,1,fade);y[-fade:]*=np.linspace(1,0,fade)
            second_ms=0
            if kind=='throw' and len(y)>int(.24*RATE):
                after=int(.21*RATE);peak=after+int(np.argmax(abs(y[after:])))
                if abs(y[peak])>abs(y).max()*.35:second_ms=max(165,int(peak*1000/RATE)-35)
            blob=np.rint(y).astype('<i2').tobytes()
            records.append({'source':src.name,'source_sha256':hashlib.sha256(src.read_bytes()).hexdigest(),'source_start_sample':start,'offset_samples':sum(len(c)//2 for c in clips),'samples':len(y),'attack_lead_ms':35,'second_pulse_ms':second_ms})
            clips.append(blob)
blob=b''.join(clips);(OUT/'dice-audio.pcm').write_bytes(blob)
(OUT/'dice-audio.json').write_text(json.dumps({'source_url':'https://kenney.nl/assets/casino-audio','creator':'Kenney','license':'CC0-1.0','sample_rate':RATE,'format':'mono signed 16-bit little endian','sha256':hashlib.sha256(blob).hexdigest(),'clips':records},indent=2)+'\n')
header=['// Generated by scripts/prepare-dice-core2-audio.py; audio is CC0 by Kenney.','#pragma once','struct DiceAudioClip { unsigned offset, samples, second_pulse_ms; };','static constexpr DiceAudioClip dice_audio_clips[] = {']
header += ['    {%d, %d, %d},'%(r['offset_samples'],r['samples'],r['second_pulse_ms']) for r in records]
header+=['};'];(OUT/'dice_audio_clips.h').write_text('\n'.join(header)+'\n')
print('Prepared',len(clips),'recorded clips:',len(blob),'bytes')
