#!/usr/bin/env python3
"""Render the original rounded 3D dice atlas offline; requires NumPy and Pillow.

The ESP32 copies RGB565 sprites, never evaluates lighting or pip geometry.
Run with the bundled document/image Python or another NumPy/Pillow environment.
"""
from pathlib import Path
import hashlib, json, math
import numpy as np
from PIL import Image
ROOT=Path(__file__).resolve().parent.parent
OUT=ROOT/'apps/dice_core2/assets'
SIZE=64; AA=3; FRAMES=96
BG=np.array([23,52,60],dtype=float)
def rotation(x,y,z):
    cx,sx=math.cos(x),math.sin(x);cy,sy=math.cos(y),math.sin(y);cz,sz=math.cos(z),math.sin(z)
    return np.array([[cz,-sz,0],[sz,cz,0],[0,0,1]])@np.array([[cy,0,sy],[0,1,0],[-sy,0,cy]])@np.array([[1,0,0],[0,cx,-sx],[0,sx,cx]])
def sdf(p):
    q=np.abs(p)-.79
    return np.linalg.norm(np.maximum(q,0),axis=-1)+np.minimum(np.max(q,axis=-1),0)-.21
axis=np.linspace(-1.70,1.70,SIZE*AA)
xx,yy=np.meshgrid(axis,axis)
world=np.stack([xx,yy,np.full_like(xx,-4)],axis=-1).reshape(-1,3)
light=np.array([-.45,-.65,-1.0]);light/=np.linalg.norm(light)
half=light+np.array([0,0,-1]);half/=np.linalg.norm(half)
def render(mat,gold=False):
    origins=world@mat;direction=np.array([0,0,1])@mat
    depth=np.zeros(len(origins));active=np.ones(len(origins),dtype=bool);hit=np.zeros_like(active)
    for _ in range(64):
        ids=np.flatnonzero(active)
        if not len(ids):break
        p=origins[ids]+depth[ids,None]*direction
        d=sdf(p);near=d<.001
        hit[ids[near]]=True;active[ids[near]]=False
        depth[ids]+=np.maximum(d,.001)
        active[depth>7]=False
    rgb=np.tile(BG,(len(origins),1))
    ids=np.flatnonzero(hit);p=origins[ids]+depth[ids,None]*direction
    normals=np.maximum(np.abs(p)-.79,0)*np.sign(p)
    normals/=np.linalg.norm(normals,axis=1)[:,None]
    n=normals@mat.T
    diffuse=np.maximum(n@light,0)
    spec=np.maximum(n@half,0)**56
    material=np.array([242,188,67] if gold else [249,246,231])
    lit=material[None,:]*(.46+.54*diffuse[:,None])+spec[:,None]*52
    # Each number is attached to its physical face; opposite faces sum to 7.
    dims=np.argmax(np.abs(p),axis=1)
    for dim,negative,positive in [(0,2,5),(1,3,4),(2,1,6)]:
        for sign,value in [(-1,negative),(1,positive)]:
            candidates=(dims==dim)&(p[:,dim]*sign>.97)
            uv=p[:,[i for i in range(3) if i!=dim]]
            centers=[]
            if value%2:centers.append((0,0))
            if value>=2:centers += [(-.48,-.48),(.48,.48)]
            if value>=4:centers += [(-.48,.48),(.48,-.48)]
            if value==6:centers += [(-.48,0),(.48,0)]
            for u,v in centers:
                dist=np.sqrt((uv[:,0]-u)**2+(uv[:,1]-v)**2)
                inside=candidates&(dist<.165)
                # Dark recess with a small lower rim reflection.
                rim=np.clip((dist-.125)/.04,0,1)
                pip=np.array([12,23,30])[None,:]+rim[:,None]*np.array([39,41,40])[None,:]
                lit[inside]=pip[inside]
    rgb[ids]=np.clip(lit,0,255)
    image=Image.fromarray(np.rint(rgb).reshape(SIZE*AA,SIZE*AA,3).astype('uint8'))
    mask=Image.fromarray((hit.reshape(SIZE*AA,SIZE*AA)*255).astype('uint8'))
    coverage.append(np.asarray(mask.resize((SIZE,SIZE),Image.Resampling.LANCZOS))>4)
    return image.resize((SIZE,SIZE),Image.Resampling.LANCZOS)
def face_pose(value):
    x,y={1:(0,0),2:(0,-math.pi/2),3:(math.pi/2,0),4:(-math.pi/2,0),5:(0,math.pi/2),6:(0,math.pi)}[value]
    return rotation(.12,-.12,0)@rotation(x,y,0)
images=[]
coverage=[]
for i in range(FRAMES):
    t=i*2*math.pi/FRAMES
    images.append(render(rotation(.5+t*2,.4+t,.3*math.sin(t))))
for gold in (False,True):
    for value in range(1,7):images.append(render(face_pose(value),gold))
OUT.mkdir(exist_ok=True)
pixels=np.stack([np.asarray(im,dtype=np.uint16) for im in images])
rgb565=((pixels[:,:,:,0]>>3)<<11)|((pixels[:,:,:,1]>>2)<<5)|(pixels[:,:,:,2]>>3)
rgb565[~np.stack(coverage)]=0
blob=rgb565.astype('>u2').tobytes()
(OUT/'dice-atlas.rgb565').write_bytes(blob)
bounds=[]
for pixels in rgb565:
    ys,xs=np.nonzero(pixels)
    bounds.append((int(xs.min()),int(ys.min()),int(xs.max()+1),int(ys.max()+1)))
(OUT/'dice_sprite_bounds.h').write_text('// Generated by scripts/render-dice-core2-atlas.py\n#pragma once\nstatic constexpr unsigned char dice_sprite_bounds[][4] = {\n'+''.join('    {%d,%d,%d,%d},\n'%b for b in bounds)+'};\n')
(OUT/'dice-atlas.json').write_text(json.dumps({'generator':'scripts/render-dice-core2-atlas.py','license':'MIT','size':SIZE,'tumble_frames':FRAMES,'rest_frames':6,'held_frames':6,'format':'RGB565 big endian','transparent':0,'sha256':hashlib.sha256(blob).hexdigest()},indent=2)+'\n')
sheet=Image.new('RGB',(SIZE*10,SIZE*((len(images)+9)//10)))
for i,im in enumerate(images):sheet.paste(im,((i%10)*SIZE,(i//10)*SIZE))
sheet.save(OUT/'dice-atlas-preview.png')
print('Rendered',len(images),'frames:',len(blob),'bytes')
