// Generated by scripts/prepare-dice-core2-audio.py; audio is CC0 by Kenney.
#pragma once
struct DiceAudioClip { unsigned offset, samples, second_pulse_ms; };
static constexpr DiceAudioClip dice_audio_clips[] = {
    {0, 5181, 0},
    {5181, 5181, 0},
    {10362, 5181, 0},
    {15543, 5181, 0},
    {20724, 5181, 0},
    {25905, 5181, 0},
    {31086, 6214, 0},
    {37300, 4344, 0},
    {41644, 11087, 196},
};
