#ifndef HOST_SDKCONFIG_H
#define HOST_SDKCONFIG_H

#define CONFIG_ESP_LCD_TOUCH_MAX_POINTS 5
#define CONFIG_ESP_LCD_TOUCH_MAX_BUTTONS 0
#define CONFIG_PLATFORM_TOUCH_ELECROW_10_1_CROSS_REVISION_AUTHORIZED 1

#endif
