#!/usr/bin/env python3
"""Generate or verify a deterministic C include for host-owned Lua source."""

from __future__ import annotations

import argparse
import hashlib
import os
from pathlib import Path
import sys


def render(source: Path) -> bytes:
    data = source.read_bytes()
    if not data or b"\0" in data:
        raise ValueError("embedded Lua source must be nonempty text without NUL")
    data.decode("utf-8")
    digest = hashlib.sha256(data).hexdigest()
    lines = [
        "/* Generated by scripts/lua/embed-lua.py; do not edit. */",
        f"/* Source: {source.as_posix()} */",
        f"/* SHA-256: {digest} */",
        "static const unsigned char P4_ARCADE_LUA_SOURCE[] = {",
    ]
    for offset in range(0, len(data), 12):
        values = ", ".join(f"0x{value:02x}" for value in data[offset:offset + 12])
        lines.append(f"    {values},")
    lines.extend([
        "};",
        "static const size_t P4_ARCADE_LUA_SOURCE_BYTES =",
        "    sizeof(P4_ARCADE_LUA_SOURCE);",
        f'static const char P4_ARCADE_LUA_SOURCE_SHA256[] = "{digest}";',
        "",
    ])
    return "\n".join(lines).encode("ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = render(arguments.source)
    if arguments.check:
        if not arguments.output.is_file() or arguments.output.read_bytes() != generated:
            raise ValueError(f"generated Lua include is stale: {arguments.output}")
        print(f"P4_LUA_EMBED_OK source={arguments.source} bytes={len(arguments.source.read_bytes())}")
        return 0
    if arguments.output.exists():
        raise ValueError(f"refusing to overwrite existing output: {arguments.output}")
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    temporary = arguments.output.with_name(f".{arguments.output.name}.{os.getpid()}.tmp")
    try:
        with temporary.open("xb") as stream:
            stream.write(generated)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, arguments.output)
    finally:
        if temporary.exists():
            temporary.unlink()
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, UnicodeDecodeError, ValueError) as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(2)
