#!/usr/bin/env python3
"""Verify/stage the arena bundle; --fetch obtains pinned external inputs only."""
from pathlib import Path
import argparse
import hashlib
import json
import shutil
import subprocess
import tempfile
import urllib.request
import zipfile

ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / "components/platform_game_storage/include/platform/doom_arena_content.h"


def bundle():
    return json.loads((ROOT / "third_party/game-data.json").read_text())["game_changers_ai_bundle"]


def header_text(data):
    files = data["files"]
    assert [f["symbol"] for f in files[:3]] == ["BASE", "PWAD", "DWANGO"]
    assert len({f["usb_kind"] for f in files}) == len(files)
    assert all(4 < f["usb_kind"] < 256 for f in files)
    identity = b"P4-GCA-ARENAS-1\0" + b"".join(bytes.fromhex(f["sha256"]) for f in files[:3])
    assert hashlib.sha256(identity).hexdigest() == data["content_sha256"]
    assert [s["id"] for s in data["selections"]] == list(range(1, 30))
    digest = bytes.fromhex(data["content_sha256"])
    lines = ["// SPDX-License-Identifier: MIT", "/* Generated by scripts/doom/arena-content.py from third_party/game-data.json. */",
             "#ifndef P4_DOOM_ARENA_CONTENT_H", "#define P4_DOOM_ARENA_CONTENT_H",
             "#define P4_GCA_CONTENT_SHA256 {" + ",".join(f"0x{b:02x}" for b in digest) + "}",
             "#define P4_GCA_CONTENT_FILES(X) \\"]
    for i, f in enumerate(data["files"]):
        lines.append(f'    X({f["usb_kind"]}, {f["symbol"]}, "{f["directory"]}", "{f["filename"]}", {f["size_bytes"]}, "{f["sha256"]}")' + (" \\" if i + 1 < len(data["files"]) else ""))
    lines += ["enum {", "#define P4_GCA_ENUM(kind, symbol, dir, name, size, hash) P4_GCA_##symbol,",
              "    P4_GCA_CONTENT_FILES(P4_GCA_ENUM)", "#undef P4_GCA_ENUM", "    P4_GCA_FILE_COUNT", "};", "#endif", ""]
    return "\n".join(lines)


def verify_vendored_pack():
    provenance = json.loads((ROOT / "third_party/pure-hades.json").read_text())
    destination = ROOT / provenance["destination"]
    for name, digest in provenance["files"].items():
        path = destination / name
        if path.is_symlink() or not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != digest:
            raise ValueError(f"Pinned Pure Hades source/release differs: {path}")


def validate(data):
    for f in data["files"]:
        path = ROOT / f["local_path"]
        if path.is_symlink() or not path.is_file():
            raise ValueError(f"Missing regular input: {path}")
        check_input_location(f)
        if path.stat().st_size != f["size_bytes"] or hashlib.sha256(path.read_bytes()).hexdigest() != f["sha256"]:
            raise ValueError(f"Wrong content identity: {path}")


def check_input_location(entry):
    if entry.get("repository_asset"):
        policy = json.loads((ROOT / "third_party/game-data.json").read_text())["policy"]
        if entry["local_path"] not in policy["repository_asset_exceptions"]:
            raise ValueError("Unlisted repository asset")
    else:
        subprocess.run(["git", "check-ignore", "-q", str(ROOT / entry["local_path"])],
                       cwd=ROOT, check=True)


def fetch(data):
    metadata = json.loads((ROOT / "third_party/game-data.json").read_text())
    freedoom = next(g for g in metadata["game_data"] if g["id"] == "freedoom-0.13.0-phase-2")["source_archive"]
    dwango = data["dwango5_source"]
    archives = [(freedoom["url"], freedoom["size_bytes"], freedoom["sha256"], {"BASE"}),
                (dwango["url"], dwango["archive_size_bytes"], dwango["archive_sha256"],
                 {"DWANGO", "DWANGO_NOTICE", "DWANGO_DIZ"})]
    # Preflight all existing files before any download or destination write.
    for f in data["files"]:
        check_input_location(f)
        p = ROOT / f["local_path"]
        if p.is_symlink() or (p.exists() and (not p.is_file() or
                p.stat().st_size != f["size_bytes"] or
                hashlib.sha256(p.read_bytes()).hexdigest() != f["sha256"])):
            raise ValueError(f"Conflicting existing content: {p}")
        if f.get("repository_asset") and not p.is_file():
            raise ValueError(f"Repository asset missing: {p}")
    for url, size, digest, symbols in archives:
        entries = [f for f in data["files"] if f["symbol"] in symbols]
        if all((ROOT / f["local_path"]).is_file() for f in entries):
            continue
        with tempfile.TemporaryDirectory(prefix="p4-arena-fetch-") as scratch:
            archive = Path(scratch) / "input.zip"
            request = urllib.request.Request(url, headers={"User-Agent": "P4-Console-Arena/1"})
            with urllib.request.urlopen(request, timeout=60) as response:
                payload = response.read(size + 1)
            if len(payload) != size or hashlib.sha256(payload).hexdigest() != digest:
                raise ValueError(f"Archive identity mismatch: {url}")
            archive.write_bytes(payload)
            verified = []
            with zipfile.ZipFile(archive) as z:
                for f in entries:
                    member = "freedoom-0.13.0/freedoom2.wad" if f["symbol"] == "BASE" else f["filename"]
                    info = z.getinfo(member)
                    if info.file_size != f["size_bytes"]:
                        raise ValueError(f"Archive member size mismatch: {member}")
                    content = z.read(info)
                    if hashlib.sha256(content).hexdigest() != f["sha256"]:
                        raise ValueError(f"Archive member hash mismatch: {member}")
                    verified.append((f, content))
            # No extractall: only named, verified members reach fixed destinations.
            for f, content in verified:
                p = ROOT / f["local_path"]
                if p.exists():
                    continue
                p.parent.mkdir(parents=True, exist_ok=True)
                with tempfile.NamedTemporaryFile(dir=p.parent, delete=False) as output:
                    temporary = Path(output.name)
                    output.write(content)
                try:
                    # Exclusive creation prevents overwriting a concurrent install.
                    import os
                    os.link(temporary, p)
                finally:
                    temporary.unlink()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--check", action="store_true", help="check metadata/header only")
    parser.add_argument("--fetch", action="store_true", help="download missing pinned Freedoom/DWANGO files")
    parser.add_argument("--stage", type=Path, help="copy verified files into an ignored local SD layout")
    args = parser.parse_args()
    verify_vendored_pack()
    data = bundle()
    if args.fetch:
        fetch(data)
    expected = header_text(data)
    if args.generate:
        HEADER.write_text(expected)
    elif HEADER.read_text() != expected:
        raise ValueError("Arena content header is stale; run --generate")
    if not args.check and not args.generate:
        validate(data)
    if args.stage:
        validate(data)
        # Complete preflight before copying anything; refuse tracked destinations.
        for f in data["files"]:
            target = args.stage.resolve() / f["directory"].lstrip("/") / f["filename"]
            subprocess.run(["git", "check-ignore", "-q", str(target)], cwd=ROOT, check=True)
            if target.exists() and hashlib.sha256(target.read_bytes()).hexdigest() != f["sha256"]:
                raise ValueError(f"Conflicting existing content: {target}")
        for f in data["files"]:
            target = args.stage.resolve() / f["directory"].lstrip("/") / f["filename"]
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(ROOT / f["local_path"], target)
    print(f'P4_ARENA_CONTENT PASS files={len(data["files"])} identity={data["content_sha256"]}')


if __name__ == "__main__":
    main()
