#!/usr/bin/env python3
"""Verify/stage Arena content; --fetch obtains pinned inputs and builds its compact base."""
from pathlib import Path
import argparse
import hashlib
import importlib.util
import json
import shutil
import subprocess
import tempfile
import urllib.request
import zipfile

ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / "components/platform_game_storage/include/platform/doom_arena_content.h"


def bundle():
    return json.loads((ROOT / "third_party/game-data.json").read_text())["game_changers_ai_bundle"]


def header_text(data, *, original=None):
    files = data["files"]
    if original is None:
        original = next(g for g in json.loads((ROOT / "third_party/game-data.json").read_text())["game_data"]
                        if g["id"] == "freedoom-0.13.0-phase-2")
    assert [f["symbol"] for f in files[:3]] == ["BASE", "PWAD", "DWANGO"]
    assert len({f["usb_kind"] for f in files}) == len(files)
    assert all(4 < f["usb_kind"] < 256 for f in files)
    identity = b"P4-GCA-ARENAS-1\0" + b"".join(bytes.fromhex(f["sha256"]) for f in files[:3])
    assert hashlib.sha256(identity).hexdigest() == data["content_sha256"]
    assert [s["id"] for s in data["selections"]] == list(range(1, 30))
    digest = bytes.fromhex(data["content_sha256"])
    lines = ["// SPDX-License-Identifier: MIT", "/* Generated by scripts/doom/arena-content.py from third_party/game-data.json. */",
             "#ifndef P4_DOOM_ARENA_CONTENT_H", "#define P4_DOOM_ARENA_CONTENT_H",
             f'#define P4_FREEDOOM2_ORIGINAL_BYTES {original["size_bytes"]}',
             f'#define P4_FREEDOOM2_ORIGINAL_SHA256_HEX "{original["sha256"]}"',
             f'#define P4_GCA_BASE_WAD_BYTES {files[0]["size_bytes"]}',
             f'#define P4_GCA_BASE_IDENTITY "{data["base_game_data_id"]}"',
             f'#define P4_GCA_BASE_SHA256_HEX "{files[0]["sha256"]}"',
             f'#define P4_GCA_BASE_SD_PATH "/game-data{files[0]["directory"]}/{files[0]["filename"]}"',
             "#define P4_GCA_CONTENT_SHA256 {" + ",".join(f"0x{b:02x}" for b in digest) + "}",
             "#define P4_GCA_CONTENT_FILES(X) \\"]
    for i, f in enumerate(data["files"]):
        lines.append(f'    X({f["usb_kind"]}, {f["symbol"]}, "{f["directory"]}", "{f["filename"]}", {f["size_bytes"]}, "{f["sha256"]}")' + (" \\" if i + 1 < len(data["files"]) else ""))
    lines += ["enum {", "#define P4_GCA_ENUM(kind, symbol, dir, name, size, hash) P4_GCA_##symbol,",
              "    P4_GCA_CONTENT_FILES(P4_GCA_ENUM)", "#undef P4_GCA_ENUM", "    P4_GCA_FILE_COUNT", "};", "#endif", ""]
    return "\n".join(lines)


def verify_vendored_pack():
    provenance = json.loads((ROOT / "third_party/pure-hades.json").read_text())
    destination = ROOT / provenance["destination"]
    for name, digest in provenance["files"].items():
        path = destination / name
        if path.is_symlink() or not path.is_file() or hashlib.sha256(path.read_bytes()).hexdigest() != digest:
            raise ValueError(f"Pinned Pure Hades source/release differs: {path}")


def validate(data):
    for f in data["files"]:
        path = ROOT / f["local_path"]
        if path.is_symlink() or not path.is_file():
            raise ValueError(f"Missing regular input: {path}")
        check_input_location(f)
        if path.stat().st_size != f["size_bytes"] or hashlib.sha256(path.read_bytes()).hexdigest() != f["sha256"]:
            raise ValueError(f"Wrong content identity: {path}")


def check_input_location(entry):
    if entry.get("repository_asset"):
        policy = json.loads((ROOT / "third_party/game-data.json").read_text())["policy"]
        if entry["local_path"] not in policy["repository_asset_exceptions"]:
            raise ValueError("Unlisted repository asset")
    else:
        subprocess.run(["git", "check-ignore", "-q", str(ROOT / entry["local_path"])],
                       cwd=ROOT, check=True)


def fetch(data):
    metadata = json.loads((ROOT / "third_party/game-data.json").read_text())
    original = next(g for g in metadata["game_data"] if g["id"] == "freedoom-0.13.0-phase-2")
    freedoom = original["source_archive"]
    compact = data.get("base_game_data_id") == "p4-arena-compact-v1"
    source_base = dict(original, symbol="BASE") if compact else data["files"][0]
    acquisition_files = [source_base] + [f for f in data["files"] if f["symbol"] != "BASE"]
    dwango = data["dwango5_source"]
    archives = [(freedoom["url"], freedoom["size_bytes"], freedoom["sha256"], {"BASE"}),
                (dwango["url"], dwango["archive_size_bytes"], dwango["archive_sha256"],
                 {"DWANGO", "DWANGO_NOTICE", "DWANGO_DIZ"})]
    # Preflight all existing files before any download or destination write.
    for f in data["files"] + ([source_base] if compact else []):
        check_input_location(f)
        p = ROOT / f["local_path"]
        if p.is_symlink() or (p.exists() and (not p.is_file() or
                p.stat().st_size != f["size_bytes"] or
                hashlib.sha256(p.read_bytes()).hexdigest() != f["sha256"])):
            raise ValueError(f"Conflicting existing content: {p}")
        if f.get("repository_asset") and not p.is_file():
            raise ValueError(f"Repository asset missing: {p}")
    for url, size, digest, symbols in archives:
        entries = [f for f in acquisition_files if f["symbol"] in symbols]
        if all((ROOT / f["local_path"]).is_file() for f in entries):
            continue
        with tempfile.TemporaryDirectory(prefix="p4-arena-fetch-") as scratch:
            archive = Path(scratch) / "input.zip"
            request = urllib.request.Request(url, headers={"User-Agent": "P4-Console-Arena/1"})
            with urllib.request.urlopen(request, timeout=60) as response:
                payload = response.read(size + 1)
            if len(payload) != size or hashlib.sha256(payload).hexdigest() != digest:
                raise ValueError(f"Archive identity mismatch: {url}")
            archive.write_bytes(payload)
            verified = []
            with zipfile.ZipFile(archive) as z:
                for f in entries:
                    member = "freedoom-0.13.0/freedoom2.wad" if f["symbol"] == "BASE" else f["filename"]
                    info = z.getinfo(member)
                    if info.file_size != f["size_bytes"]:
                        raise ValueError(f"Archive member size mismatch: {member}")
                    content = z.read(info)
                    if hashlib.sha256(content).hexdigest() != f["sha256"]:
                        raise ValueError(f"Archive member hash mismatch: {member}")
                    verified.append((f, content))
            # No extractall: only named, verified members reach fixed destinations.
            for f, content in verified:
                p = ROOT / f["local_path"]
                if p.exists():
                    continue
                p.parent.mkdir(parents=True, exist_ok=True)
                with tempfile.NamedTemporaryFile(dir=p.parent, delete=False) as output:
                    temporary = Path(output.name)
                    output.write(content)
                try:
                    # Exclusive creation prevents overwriting a concurrent install.
                    import os
                    os.link(temporary, p)
                finally:
                    temporary.unlink()


    if compact:
        derive_compact_base(data)


def derive_compact_base(data):
    """Rebuild from exact original inputs; never reinterpret the upstream IWAD."""
    spec = importlib.util.spec_from_file_location("arena_compact", ROOT / "scripts/doom/arena-compact.py")
    generator = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(generator)
    recipe_bytes = generator.RECIPE.read_bytes()
    recipe = generator.load_recipe(recipe_bytes)
    entry = data["files"][0]
    for key in ("local_path", "size_bytes", "sha256"):
        if entry[key] != recipe["output"][key]:
            raise ValueError(f"Compact manifest/recipe mismatch: {key}")
    _, candidate = generator.analyze(recipe_bytes)
    generator.require_recipe_unchanged(recipe_bytes)
    generator.install_generated(ROOT / entry["local_path"], candidate)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--check", action="store_true", help="check metadata/header only")
    parser.add_argument("--fetch", action="store_true", help="download pinned original inputs and generate the separate compact Arena base")
    parser.add_argument("--stage", type=Path, help="copy verified files into an ignored local SD layout")
    args = parser.parse_args()
    verify_vendored_pack()
    metadata = json.loads((ROOT / "third_party/game-data.json").read_text())
    data = metadata["game_changers_ai_bundle"]
    original = next(g for g in metadata["game_data"] if g["id"] == "freedoom-0.13.0-phase-2")
    if args.fetch:
        fetch(data)
    expected = header_text(data, original=original)
    if args.generate:
        HEADER.write_text(expected)
    elif HEADER.read_text() != expected:
        raise ValueError("Arena content header is stale; run --generate")
    if not args.check and not args.generate:
        validate(data)
    if args.stage:
        validate(data)
        # Complete preflight before copying anything; refuse tracked destinations.
        for f in data["files"]:
            target = args.stage.resolve() / f["directory"].lstrip("/") / f["filename"]
            subprocess.run(["git", "check-ignore", "-q", str(target)], cwd=ROOT, check=True)
            if target.is_symlink() or (target.exists() and (not target.is_file() or hashlib.sha256(target.read_bytes()).hexdigest() != f["sha256"])):
                raise ValueError(f"Conflicting existing content: {target}")
        for f in data["files"]:
            target = args.stage.resolve() / f["directory"].lstrip("/") / f["filename"]
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(ROOT / f["local_path"], target)
    print(f'P4_ARENA_CONTENT PASS files={len(data["files"])} identity={data["content_sha256"]}')


if __name__ == "__main__":
    main()
