#!/usr/bin/env python3
"""Verify/stage the local arena bundle; never downloads or writes a device."""
from pathlib import Path
import argparse
import hashlib
import json
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[2]
HEADER = ROOT / "components/platform_game_storage/include/platform/doom_arena_content.h"


def bundle():
    return json.loads((ROOT / "third_party/game-data.json").read_text())["game_changers_ai_bundle"]


def header_text(data):
    files = data["files"]
    assert [f["symbol"] for f in files[:3]] == ["BASE", "PWAD", "DWANGO"]
    assert len({f["usb_kind"] for f in files}) == len(files)
    assert all(4 < f["usb_kind"] < 256 for f in files)
    identity = b"P4-GCA-ARENAS-1\0" + b"".join(bytes.fromhex(f["sha256"]) for f in files[:3])
    assert hashlib.sha256(identity).hexdigest() == data["content_sha256"]
    assert [s["id"] for s in data["selections"]] == list(range(1, 27))
    digest = bytes.fromhex(data["content_sha256"])
    lines = ["// SPDX-License-Identifier: MIT", "/* Generated by scripts/doom/arena-content.py from third_party/game-data.json. */",
             "#ifndef P4_DOOM_ARENA_CONTENT_H", "#define P4_DOOM_ARENA_CONTENT_H",
             "#define P4_GCA_CONTENT_SHA256 {" + ",".join(f"0x{b:02x}" for b in digest) + "}",
             "#define P4_GCA_CONTENT_FILES(X) \\"]
    for i, f in enumerate(data["files"]):
        lines.append(f'    X({f["usb_kind"]}, {f["symbol"]}, "{f["directory"]}", "{f["filename"]}", {f["size_bytes"]}, "{f["sha256"]}")' + (" \\" if i + 1 < len(data["files"]) else ""))
    lines += ["enum {", "#define P4_GCA_ENUM(kind, symbol, dir, name, size, hash) P4_GCA_##symbol,",
              "    P4_GCA_CONTENT_FILES(P4_GCA_ENUM)", "#undef P4_GCA_ENUM", "    P4_GCA_FILE_COUNT", "};", "#endif", ""]
    return "\n".join(lines)


def validate(data):
    for f in data["files"]:
        path = ROOT / f["local_path"]
        if path.is_symlink() or not path.is_file():
            raise ValueError(f"Missing regular input: {path}")
        subprocess.run(["git", "check-ignore", "-q", str(path)], cwd=ROOT, check=True)
        if path.stat().st_size != f["size_bytes"] or hashlib.sha256(path.read_bytes()).hexdigest() != f["sha256"]:
            raise ValueError(f"Wrong content identity: {path}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--generate", action="store_true")
    parser.add_argument("--check", action="store_true", help="check metadata/header only")
    parser.add_argument("--stage", type=Path, help="copy verified files into an ignored local SD layout")
    args = parser.parse_args()
    data = bundle()
    expected = header_text(data)
    if args.generate:
        HEADER.write_text(expected)
    elif HEADER.read_text() != expected:
        raise ValueError("Arena content header is stale; run --generate")
    if not args.check and not args.generate:
        validate(data)
    if args.stage:
        validate(data)
        # Complete preflight before copying anything; refuse tracked destinations.
        for f in data["files"]:
            target = args.stage.resolve() / f["directory"].lstrip("/") / f["filename"]
            subprocess.run(["git", "check-ignore", "-q", str(target)], cwd=ROOT, check=True)
            if target.exists() and hashlib.sha256(target.read_bytes()).hexdigest() != f["sha256"]:
                raise ValueError(f"Conflicting existing content: {target}")
        for f in data["files"]:
            target = args.stage.resolve() / f["directory"].lstrip("/") / f["filename"]
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(ROOT / f["local_path"], target)
    print(f'P4_ARENA_CONTENT PASS files={len(data["files"])} identity={data["content_sha256"]}')


if __name__ == "__main__":
    main()
