#!/usr/bin/env python3
"""Convert the shared transparent ImageGen effect atlas to RGB565."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

WIDTH = 160
HEIGHT = 160


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} INPUT.png OUTPUT.inc", file=sys.stderr)
        return 2
    raw = subprocess.run(
        ["ffmpeg", "-loglevel", "error", "-i", sys.argv[1],
         "-vf", f"scale={WIDTH}:{HEIGHT}:flags=neighbor", "-pix_fmt", "rgba",
         "-f", "rawvideo", "pipe:1"],
        check=True, stdout=subprocess.PIPE,
    ).stdout
    if len(raw) != WIDTH * HEIGHT * 4:
        raise RuntimeError("ffmpeg did not emit the expected RGBA atlas")
    values = []
    for offset in range(0, len(raw), 4):
        red, green, blue, alpha = raw[offset : offset + 4]
        values.append(0 if alpha < 128 else rgb565(red, green, blue))
    lines = [
        "/* Generated by tools/png_to_feedback_atlas.py; do not edit. */",
        "static const uint16_t s_p4_game_feedback_atlas[160U * 160U] = {",
    ]
    for offset in range(0, len(values), 12):
        lines.append("    " + ", ".join(
            f"UINT16_C(0x{value:04x})" for value in values[offset : offset + 12]
        ) + ",")
    lines.append("};")
    Path(sys.argv[2]).write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
