#!/usr/bin/env python3
"""Build bounded Console API PCM effect samples from the original WAV sources."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

SAMPLE_RATE = 16000
VOLUME = "0.55"
SPECS = (
    ("p4_action_original_v1.wav", "p4_action", "0.65"),
    ("p4_impact_original_v1.wav", "p4_impact", "0.72"),
    ("p4_reward_original_v1.wav", "p4_reward", "0.80"),
    ("p4_fail_original_v1.wav", "p4_fail", "0.48"),
)


def pcm_samples(source: Path, duration_seconds: str) -> list[int]:
    raw = subprocess.run(
        ["ffmpeg", "-loglevel", "error", "-i", str(source),
         "-t", duration_seconds, "-af", f"volume={VOLUME}",
         "-ar", str(SAMPLE_RATE), "-ac", "1", "-f", "s16le", "pipe:1"],
        check=True, stdout=subprocess.PIPE,
    ).stdout
    if len(raw) == 0 or len(raw) % 2 != 0:
        raise RuntimeError(f"{source} did not produce PCM16 samples")
    return [int.from_bytes(raw[offset : offset + 2], "little", signed=True)
            for offset in range(0, len(raw), 2)]


def main() -> int:
    if len(sys.argv) != 3:
        print(f"usage: {sys.argv[0]} SOURCE_DIR OUTPUT.inc", file=sys.stderr)
        return 2
    source_dir = Path(sys.argv[1])
    output = Path(sys.argv[2])
    lines = [
        "/* Generated by tools/wav_to_audio_pack.py; do not edit. */",
        "/* 16 kHz mono PCM16, source WAVs retained under assets/audio/source/. */",
    ]
    for filename, symbol, duration in SPECS:
        samples = pcm_samples(source_dir / filename, duration)
        lines.append(f"static const int16_t s_{symbol}_samples[{len(samples)}U] = {{")
        for offset in range(0, len(samples), 12):
            row = samples[offset : offset + 12]
            lines.append("    " + ", ".join(str(sample) for sample in row) + ",")
        lines.append("};")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
